-- Reduce writes generated by frequent state polling without changing room identity,
-- role permissions, the phase machine, or online indicators (12s VA / 8s PP).
-- Calls made more often than the heartbeat threshold still read the latest game state.

CREATE OR REPLACE FUNCTION app_private.get_va_banque_state_internal(p_code text, p_player_token uuid DEFAULT NULL::uuid, p_host_token uuid DEFAULT NULL::uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'app_private', 'pg_temp'
AS $function$
declare
  r app_private.platform_rooms%rowtype;
  g app_private.va_banque_games%rowtype;
  q app_private.va_banque_questions%rowtype;
  viewer app_private.room_players%rowtype;
  vp app_private.va_banque_players%rowtype;
  v_players jsonb;
  v_bids jsonb;
  v_final_answers jsonb;
  v_show_question boolean;
  v_show_solution boolean;
  v_is_host boolean := false;
begin
  perform app_private.va_banque_tick_internal(p_code);

  select * into r
  from app_private.platform_rooms
  where code=upper(trim(p_code))
    and game_slug='va-banque'
    and status='active'
    and expires_at>now()
  limit 1;

  if r.id is null then return null; end if;

  v_is_host := p_host_token is not null and r.host_token=p_host_token;

  if p_player_token is not null then
    select * into viewer
    from app_private.room_players
    where room_id=r.id and player_token=p_player_token
    limit 1;

    if viewer.id is null then
      raise exception 'Player not found';
    end if;

    update app_private.room_players
    set last_seen_at=now()
    where id=viewer.id
      and (last_seen_at is null or last_seen_at < now() - interval '4 seconds');

    select * into vp
    from app_private.va_banque_players
    where room_id=r.id and player_id=viewer.id;
  elsif not v_is_host then
    raise exception 'Access denied';
  end if;

  select * into g from app_private.va_banque_games where room_id=r.id;
  select * into q from app_private.va_banque_questions where id=g.question_id;

  v_show_question := g.phase in (
    'question','main_result','takeover_open','takeover_question',
    'takeover_result','round_result','final_question','final_reveal','finished'
  );
  v_show_solution :=
    g.phase in ('takeover_result','round_result','final_reveal','finished')
    or (g.phase='main_result' and g.last_event->>'type'='main_correct');

  select jsonb_agg(
    jsonb_build_object(
      'id',p.player_id,
      'name',rp.display_name,
      'avatar',rp.avatar,
      'points',p.points,
      'isConnected',rp.last_seen_at > now()-interval '12 seconds'
    )
    order by p.points desc,rp.joined_at asc
  ) into v_players
  from app_private.va_banque_players p
  join app_private.room_players rp on rp.id=p.player_id
  where p.room_id=r.id;

  if g.phase in ('bid_reveal','tie_bid','tie_reveal','question','main_result','takeover_open','takeover_question','takeover_result','round_result') then
    select jsonb_agg(
      jsonb_build_object(
        'playerId',p.player_id,
        'bid',p.bid,
        'tieBid',case when g.phase <> 'tie_bid' and p.tie_locked then p.tie_bid else null end
      )
      order by rp.joined_at
    ) into v_bids
    from app_private.va_banque_players p
    join app_private.room_players rp on rp.id=p.player_id
    where p.room_id=r.id;
  else
    v_bids:='[]'::jsonb;
  end if;

  if g.phase in ('final_reveal','finished') then
    select jsonb_agg(
      jsonb_build_object(
        'playerId',p.player_id,
        'bid',p.final_bid,
        'answerIndex',p.final_answer_index,
        'correct',p.final_answer_index=q.correct_index
      )
      order by rp.joined_at
    ) into v_final_answers
    from app_private.va_banque_players p
    join app_private.room_players rp on rp.id=p.player_id
    where p.room_id=r.id;
  else
    v_final_answers:='[]'::jsonb;
  end if;

  return jsonb_build_object(
    'serverNow',now(),
    'phase',g.phase,
    'deadline',g.phase_deadline,
    'roundIndex',g.round_index,
    'regularRounds',g.regular_rounds,
    'category',q.category,
    'difficulty',q.difficulty,
    'question',case when v_show_question then q.prompt else null end,
    'options',case when v_show_question then q.options else '[]'::jsonb end,
    'correctIndex',case when v_show_solution then q.correct_index else null end,
    'explanation',case when v_show_solution then q.explanation else null end,
    'players',coalesce(v_players,'[]'::jsonb),
    'bids',coalesce(v_bids,'[]'::jsonb),
    'winningPlayerId',g.winning_player_id,
    'winningBid',g.winning_bid,
    'tiePlayerIds',to_jsonb(g.tie_player_ids),
    'takeoverPlayerId',g.takeover_player_id,
    'takeoverRisk',g.takeover_risk,
    'lastEvent',g.last_event,
    'finalAnswers',coalesce(v_final_answers,'[]'::jsonb),
    'isHost',v_is_host,
    'viewer',case when viewer.id is null then null else jsonb_build_object(
      'id',viewer.id,
      'name',viewer.display_name,
      'avatar',viewer.avatar,
      'points',vp.points,
      'bid',vp.bid,
      'bidLocked',vp.bid_locked,
      'tieBid',vp.tie_bid,
      'tieLocked',vp.tie_locked,
      'answerIndex',vp.answer_index,
      'answerLocked',vp.answer_locked,
      'finalBid',vp.final_bid,
      'finalBidLocked',vp.final_bid_locked,
      'finalAnswerIndex',vp.final_answer_index,
      'finalAnswerLocked',vp.final_answer_locked
    ) end
  );
end;
$function$;

CREATE OR REPLACE FUNCTION app_private.get_pp_state_internal(p_code text, p_player_token uuid DEFAULT NULL::uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'app_private', 'pg_temp'
AS $function$
declare
  r app_private.platform_rooms%rowtype;
  s app_private.pp_game_state%rowtype;
  me app_private.room_players%rowtype;
  my_role text;
  m app_private.pp_missions%rowtype;
  current_modifier text := 'normal';
  current_stage text;
  player_count integer;
  submitted_count integer;
  voted_count integer;
  skipped_count integer;
  current_vote_type text;
  payload jsonb;
  saboteur_id uuid;
  saboteur_name text;
  interrogation_name text;
  interrogation_avatar text;
  spotlight_name text;
  spotlight_avatar text;
  defender_one_name text;
  defender_one_avatar text;
  defender_two_name text;
  defender_two_avatar text;
  accused_name text;
  accused_avatar text;
  final_counts jsonb := '[]'::jsonb;
  suspicion_counts jsonb := '[]'::jsonb;
  cumulative_suspicion_counts jsonb := '[]'::jsonb;
begin
  select * into r
  from app_private.platform_rooms
  where code=upper(trim(p_code))
    and game_slug='pod-przykrywka'
    and expires_at > now()
  limit 1;

  if r.id is null then return null; end if;

  select * into s from app_private.pp_game_state where room_id=r.id;
  if s.room_id is null then return null; end if;

  if p_player_token is not null then
    select * into me
    from app_private.room_players
    where room_id=r.id and player_token=p_player_token
    limit 1;

    if me.id is not null then
      update app_private.room_players
      set last_seen_at=now()
      where id=me.id
        and (last_seen_at is null or last_seen_at < now() - interval '3 seconds');
      select role into my_role
      from app_private.pp_roles
      where room_id=r.id and player_id=me.id;
    end if;
  end if;

  select pm.* into m
  from app_private.pp_game_missions gm
  join app_private.pp_missions pm on pm.id=gm.mission_id
  where gm.room_id=r.id and gm.position=s.mission_index
  limit 1;

  select gm.modifier into current_modifier
  from app_private.pp_game_missions gm
  where gm.room_id=r.id and gm.position=s.mission_index
  limit 1;

  current_modifier := coalesce(current_modifier,'normal');

  current_stage := case
    when s.phase='mission' then 'answer'
    when s.phase='final_vote' then 'final'
    else 'suspicion'
  end;

  if s.interrogation_player_id is not null then
    select display_name, avatar into interrogation_name, interrogation_avatar
    from app_private.room_players
    where id=s.interrogation_player_id and room_id=r.id limit 1;
  end if;

  if s.spotlight_player_id is not null then
    select display_name, avatar into spotlight_name, spotlight_avatar
    from app_private.room_players
    where id=s.spotlight_player_id and room_id=r.id limit 1;
  end if;

  if s.final_defender_one_id is not null then
    select display_name, avatar into defender_one_name, defender_one_avatar
    from app_private.room_players
    where id=s.final_defender_one_id and room_id=r.id limit 1;
  end if;

  if s.final_defender_two_id is not null then
    select display_name, avatar into defender_two_name, defender_two_avatar
    from app_private.room_players
    where id=s.final_defender_two_id and room_id=r.id limit 1;
  end if;

  if s.final_target_player_id is not null then
    select display_name, avatar into accused_name, accused_avatar
    from app_private.room_players
    where id=s.final_target_player_id and room_id=r.id limit 1;
  end if;

  select count(*) into player_count
  from app_private.room_players
  where room_id=r.id;

  select count(*) into submitted_count
  from app_private.pp_submissions
  where room_id=r.id and mission_index=s.mission_index;

  current_vote_type := case
    when s.phase in ('final_vote','final_locked','final_accused','result') then 'final'
    else 'suspicion'
  end;

  select count(*) into voted_count
  from app_private.pp_votes
  where room_id=r.id
    and mission_index=s.mission_index
    and vote_type=current_vote_type;

  select count(*) into skipped_count
  from app_private.pp_skipped_actions
  where room_id=r.id and mission_index=s.mission_index and stage=current_stage;

  if s.phase in (
    'suspicion_result','checkpoint','interrogation','last_word',
    'final_defense_intro','final_defense_one','final_defense_two',
    'final_vote','final_locked','final_accused','result'
  ) then
    select coalesce(jsonb_agg(x order by x.votes desc, x.display_name), '[]'::jsonb)
    into suspicion_counts
    from (
      select p.id as player_id, p.display_name, p.avatar, count(v.target_player_id)::integer as votes
      from app_private.room_players p
      left join app_private.pp_votes v
        on v.room_id=r.id
       and v.mission_index=s.mission_index
       and v.vote_type='suspicion'
       and v.target_player_id=p.id
      where p.room_id=r.id
      group by p.id,p.display_name,p.avatar
    ) x;

    select coalesce(jsonb_agg(x order by x.votes desc, x.display_name), '[]'::jsonb)
    into cumulative_suspicion_counts
    from (
      select p.id as player_id, p.display_name, p.avatar, count(v.target_player_id)::integer as votes
      from app_private.room_players p
      left join app_private.pp_votes v
        on v.room_id=r.id
       and v.mission_index <= s.mission_index
       and v.vote_type='suspicion'
       and v.target_player_id=p.id
      where p.room_id=r.id
      group by p.id,p.display_name,p.avatar
    ) x;
  end if;

  if s.phase='result' then
    select rr.player_id, p.display_name
      into saboteur_id, saboteur_name
    from app_private.pp_roles rr
    join app_private.room_players p on p.id=rr.player_id
    where rr.room_id=r.id and rr.role='saboteur'
    limit 1;

    select coalesce(jsonb_agg(x order by x.votes desc, x.display_name), '[]'::jsonb)
    into final_counts
    from (
      select p.id as player_id, p.display_name, p.avatar, count(v.target_player_id)::integer as votes
      from app_private.room_players p
      left join app_private.pp_votes v
        on v.room_id=r.id
       and v.vote_type='final'
       and v.target_player_id=p.id
      where p.room_id=r.id
      group by p.id,p.display_name,p.avatar
    ) x;
  end if;

  payload := jsonb_build_object(
    'phase', s.phase,
    'phaseStartedAt', s.phase_started_at,
    'phaseTimeBonusSeconds', s.phase_time_bonus_seconds,
    'missionIndex', s.mission_index + 1,
    'missionCount', 5,
    'playerCount', player_count,
    'submittedCount', submitted_count,
    'votedCount', voted_count,
    'skippedCount', skipped_count,
    'players', (
      select coalesce(jsonb_agg(jsonb_build_object(
        'id',p.id,
        'displayName',p.display_name,
        'avatar',p.avatar,
        'submitted', exists(
          select 1 from app_private.pp_submissions sub
          where sub.room_id=r.id and sub.mission_index=s.mission_index and sub.player_id=p.id
        ),
        'voted', exists(
          select 1 from app_private.pp_votes v
          where v.room_id=r.id and v.mission_index=s.mission_index
            and v.vote_type=current_vote_type and v.voter_player_id=p.id
        ),
        'online', p.last_seen_at > now() - interval '8 seconds',
        'lastSeenAt', p.last_seen_at,
        'skipped', exists(
          select 1 from app_private.pp_skipped_actions sk
          where sk.room_id=r.id and sk.mission_index=s.mission_index
            and sk.stage=current_stage and sk.player_id=p.id
        )
      ) order by p.joined_at), '[]'::jsonb)
      from app_private.room_players p
      where p.room_id=r.id
    ),
    'mission', case
      when s.phase='briefing' then null
      else jsonb_build_object(
        'category',m.category,
        'title',m.title,
        'briefing',m.briefing,
        'prompt',case
          when me.id is null then m.briefing
          when my_role='saboteur' then m.saboteur_prompt
          else m.agent_prompt
        end,
        'placeholder',m.placeholder,
        'responseMode',m.response_mode,
        'options',m.options,
        'discussionPrompts',m.discussion_prompts,
        'modifier',current_modifier
      )
    end,
    'currentPlayer', case when me.id is null then null else jsonb_build_object(
      'id',me.id,
      'displayName',me.display_name,
      'avatar',me.avatar,
      'role',my_role,
      'answer',(
        select sub.answer
        from app_private.pp_submissions sub
        where sub.room_id=r.id and sub.mission_index=s.mission_index and sub.player_id=me.id
      ),
      'voteTargetId',(
        select v.target_player_id
        from app_private.pp_votes v
        where v.room_id=r.id and v.mission_index=s.mission_index
          and v.vote_type=current_vote_type and v.voter_player_id=me.id
      )
    ) end,
    'submissions', case
      when s.phase in (
        'evidence','spotlight','suspicion','suspicion_result','checkpoint','interrogation','last_word',
        'final_defense_intro','final_defense_one','final_defense_two',
        'final_vote','final_locked','final_accused','result'
      ) then (
        case
          when current_modifier='anonymous' and s.phase='evidence' then (
            select coalesce(jsonb_agg(jsonb_build_object(
              'playerId','anon-' || a.rn,
              'displayName','Odpowiedź ' || chr(64 + a.rn),
              'avatar','hidden',
              'answer',a.answer
            ) order by a.rn), '[]'::jsonb)
            from (
              select sub.answer, row_number() over(order by md5(sub.player_id::text || r.id::text || s.mission_index::text))::integer as rn
              from app_private.pp_submissions sub
              where sub.room_id=r.id and sub.mission_index=s.mission_index
            ) a
          )
          else (
            select coalesce(jsonb_agg(jsonb_build_object(
              'playerId',p.id,
              'displayName',p.display_name,
              'avatar',p.avatar,
              'answer',sub.answer
            ) order by p.joined_at), '[]'::jsonb)
            from app_private.room_players p
            join app_private.pp_submissions sub
              on sub.player_id=p.id and sub.room_id=r.id and sub.mission_index=s.mission_index
            where p.room_id=r.id
          )
        end
      )
      else '[]'::jsonb
    end,
    'suspicion', suspicion_counts,
    'cumulativeSuspicion', cumulative_suspicion_counts,
    'twist', jsonb_build_object(
      'interrogationPlayerId',s.interrogation_player_id,
      'interrogationPlayerName',interrogation_name,
      'interrogationPlayerAvatar',interrogation_avatar,
      'interrogationQuestion',s.interrogation_question,
      'isCurrentPlayerTarget',case when me.id is null then false else me.id=s.interrogation_player_id end,
      'spotlightPlayerId',s.spotlight_player_id,
      'spotlightPlayerName',spotlight_name,
      'spotlightPlayerAvatar',spotlight_avatar,
      'spotlightQuestion',s.spotlight_question,
      'isCurrentPlayerSpotlight',case when me.id is null then false else me.id=s.spotlight_player_id end,
      'secretOrder',case
        when my_role='saboteur' and s.mission_index >= 3 and s.phase <> 'result' then s.secret_order
        when s.phase='result' then s.secret_order
        else null
      end,
      'finalDefenderOneId',s.final_defender_one_id,
      'finalDefenderOneName',defender_one_name,
      'finalDefenderOneAvatar',defender_one_avatar,
      'finalDefenderTwoId',s.final_defender_two_id,
      'finalDefenderTwoName',defender_two_name,
      'finalDefenderTwoAvatar',defender_two_avatar,
      'activeFinalDefenderId',case
        when s.phase='final_defense_one' then s.final_defender_one_id
        when s.phase='final_defense_two' then s.final_defender_two_id
        else null
      end,
      'isCurrentPlayerFinalDefender',case
        when me.id is null then false
        when s.phase='final_defense_one' then me.id=s.final_defender_one_id
        when s.phase='final_defense_two' then me.id=s.final_defender_two_id
        else false
      end,
      'finalTie',case
        when s.phase in ('final_locked','final_accused','result') then s.final_target_player_id is null
        else false
      end,
      'finalAccusedPlayerId',case when s.phase in ('final_accused','result') then s.final_target_player_id else null end,
      'finalAccusedPlayerName',case when s.phase in ('final_accused','result') then accused_name else null end,
      'finalAccusedPlayerAvatar',case when s.phase in ('final_accused','result') then accused_avatar else null end
    ),
    'result', case when s.phase='result' then jsonb_build_object(
      'saboteurId',saboteur_id,
      'saboteurName',saboteur_name,
      'caught',coalesce(s.saboteur_caught,false),
      'finalTargetPlayerId',s.final_target_player_id,
      'finalVotes',final_counts,
      'secretOrder',s.secret_order
    ) else null end
  );

  return payload;
end;
$function$;
