-- VA BANQUE — server-authoritative multiplayer game.
-- All critical state stays in app_private and is exposed only through narrow RPCs.

alter table app_private.platform_rooms
  drop constraint if exists platform_rooms_game_slug_check;

alter table app_private.platform_rooms
  add constraint platform_rooms_game_slug_check
  check (game_slug in (
    'co-ludzie-powiedza',
    'zakrecone-haslo',
    'pod-przykrywka',
    'akta-nocy',
    'tylko-my',
    'va-banque'
  ));

create table if not exists app_private.va_banque_questions (
  id bigint generated by default as identity primary key,
  question_key text not null unique,
  category text not null,
  prompt text not null,
  options jsonb not null check (jsonb_typeof(options) = 'array' and jsonb_array_length(options) = 4),
  correct_index smallint not null check (correct_index between 0 and 3),
  difficulty text not null check (difficulty in ('easy','medium','hard')),
  explanation text not null default ''
);

alter table app_private.va_banque_questions enable row level security;
revoke all on app_private.va_banque_questions from public, anon, authenticated;

drop policy if exists "deny direct client access" on app_private.va_banque_questions;
create policy "deny direct client access"
on app_private.va_banque_questions
for all
to anon, authenticated
using (false)
with check(false);

create table if not exists app_private.va_banque_games (
  room_id uuid primary key references app_private.platform_rooms(id) on delete cascade,
  round_index integer not null default 1,
  regular_rounds integer not null,
  phase text not null default 'intro',
  phase_deadline timestamptz not null,
  question_id bigint references app_private.va_banque_questions(id),
  previous_category text,
  used_question_ids bigint[] not null default '{}',
  winning_player_id uuid references app_private.room_players(id),
  winning_bid integer,
  tie_player_ids uuid[] not null default '{}',
  takeover_player_id uuid references app_private.room_players(id),
  takeover_risk integer,
  last_event jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (phase in (
    'intro','category','bidding','bid_reveal','tie_bid','tie_reveal',
    'question','main_result','takeover_open','takeover_question',
    'takeover_result','round_result','final_category','final_bidding',
    'final_question','final_reveal','finished'
  ))
);

alter table app_private.va_banque_games enable row level security;
revoke all on app_private.va_banque_games from public, anon, authenticated;

drop policy if exists "deny direct client access" on app_private.va_banque_games;
create policy "deny direct client access"
on app_private.va_banque_games
for all
to anon, authenticated
using (false)
with check(false);

create table if not exists app_private.va_banque_players (
  room_id uuid not null references app_private.platform_rooms(id) on delete cascade,
  player_id uuid not null references app_private.room_players(id) on delete cascade,
  points integer not null default 2000 check (points >= 0),
  bid integer,
  bid_locked boolean not null default false,
  tie_bid integer,
  tie_locked boolean not null default false,
  answer_index smallint,
  answer_locked boolean not null default false,
  final_bid integer,
  final_bid_locked boolean not null default false,
  final_answer_index smallint,
  final_answer_locked boolean not null default false,
  primary key (room_id, player_id)
);

alter table app_private.va_banque_players enable row level security;
revoke all on app_private.va_banque_players from public, anon, authenticated;

drop policy if exists "deny direct client access" on app_private.va_banque_players;
create policy "deny direct client access"
on app_private.va_banque_players
for all
to anon, authenticated
using (false)
with check(false);

create index if not exists va_banque_questions_category_idx
  on app_private.va_banque_questions(category);
create index if not exists va_banque_players_player_idx
  on app_private.va_banque_players(player_id);
create index if not exists va_banque_games_question_idx
  on app_private.va_banque_games(question_id);
create index if not exists va_banque_games_winner_idx
  on app_private.va_banque_games(winning_player_id);
create index if not exists va_banque_games_takeover_idx
  on app_private.va_banque_games(takeover_player_id);

insert into app_private.va_banque_questions
(question_key, category, prompt, options, correct_index, difficulty, explanation)
values
('film_01','FILMY','Kto wyreżyserował film „Titanic”?','["Steven Spielberg","James Cameron","Ridley Scott","Peter Jackson"]',1,'easy','„Titanic” z 1997 roku wyreżyserował James Cameron.'),
('film_02','FILMY','Który film zdobył Oscara za najlepszy film na gali w 2020 roku?','["1917","Joker","Parasite","Ford v Ferrari"]',2,'medium','„Parasite” był pierwszym nieanglojęzycznym laureatem Oscara za najlepszy film.'),
('film_03','FILMY','Jak nazywa się hobbit grany przez Elijaha Wooda w trylogii „Władca Pierścieni”?','["Bilbo Baggins","Frodo Baggins","Samwise Gamgee","Peregrin Took"]',1,'easy','Elijah Wood zagrał Froda Bagginsa.'),
('film_04','FILMY','W którym filmie pada słynne „I’ll be back” Arnolda Schwarzeneggera?','["Predator","Commando","Terminator","Pamięć absolutna"]',2,'medium','Zdanie pada w filmie „Terminator” z 1984 roku.'),
('film_05','FILMY','Która aktorka zagrała Hermionę Granger w serii filmów o Harrym Potterze?','["Emma Stone","Emma Watson","Keira Knightley","Natalie Portman"]',1,'easy','Hermionę zagrała Emma Watson.'),
('film_06','FILMY','Jak nazywa się fikcyjny park z dinozaurami z filmu Stevena Spielberga z 1993 roku?','["Dino World","Jurassic Park","Cretaceous Park","Isla Park"]',1,'easy','Film nosi tytuł „Jurassic Park”.'),

('geo_01','GEOGRAFIA','Która rzeka przepływa przez Paryż?','["Ren","Sekwana","Loara","Rodan"]',1,'easy','Przez Paryż przepływa Sekwana.'),
('geo_02','GEOGRAFIA','Jaką stolicę ma Australia?','["Sydney","Melbourne","Canberra","Perth"]',2,'easy','Stolicą Australii jest Canberra.'),
('geo_03','GEOGRAFIA','Na którym kontynencie leży pustynia Atakama?','["Afryka","Azja","Ameryka Południowa","Australia"]',2,'medium','Atakama znajduje się głównie w północnym Chile.'),
('geo_04','GEOGRAFIA','Które państwo ma kształt charakterystycznego „buta”?','["Grecja","Włochy","Portugalia","Chorwacja"]',1,'easy','Chodzi o Włochy.'),
('geo_05','GEOGRAFIA','Który ocean leży między Afryką, Azją i Australią?','["Atlantycki","Arktyczny","Indyjski","Spokojny"]',2,'easy','To Ocean Indyjski.'),
('geo_06','GEOGRAFIA','Które pasmo górskie oddziela w dużej części Francję od Hiszpanii?','["Alpy","Pireneje","Karpaty","Apeniny"]',1,'medium','Granica Francji i Hiszpanii biegnie przez Pireneje.'),

('music_01','MUZYKA','Który zespół nagrał utwór „Bohemian Rhapsody”?','["The Beatles","Queen","ABBA","U2"]',1,'easy','„Bohemian Rhapsody” to utwór zespołu Queen.'),
('music_02','MUZYKA','Jak miał na imię Mozart?','["Johann Sebastian","Ludwig","Wolfgang Amadeus","Antonio"]',2,'easy','Pełne imiona kompozytora to Wolfgang Amadeus Mozart.'),
('music_03','MUZYKA','Który instrument ma standardowo 88 klawiszy?','["Fortepian","Akordeon","Organy Hammonda","Ksylofon"]',0,'easy','Standardowy współczesny fortepian ma 88 klawiszy.'),
('music_04','MUZYKA','Która grupa stworzyła przebój „Dancing Queen”?','["Boney M.","ABBA","Bee Gees","Roxette"]',1,'easy','„Dancing Queen” jest jednym z największych hitów ABBY.'),
('music_05','MUZYKA','Z jakim gatunkiem muzycznym najmocniej kojarzony jest Bob Marley?','["Reggae","Jazz","Heavy metal","Country"]',0,'easy','Bob Marley jest ikoną reggae.'),
('music_06','MUZYKA','Który kompozytor napisał „Cztery pory roku”?','["Vivaldi","Chopin","Bach","Beethoven"]',0,'medium','Cykl koncertów „Cztery pory roku” skomponował Antonio Vivaldi.'),

('hist_01','HISTORIA','W którym roku rozpoczęła się II wojna światowa w Europie?','["1918","1933","1939","1945"]',2,'easy','Niemcy zaatakowały Polskę 1 września 1939 roku.'),
('hist_02','HISTORIA','Które starożytne miasto zostało zasypane po erupcji Wezuwiusza w 79 roku?','["Sparta","Pompeje","Teby","Kartagina"]',1,'easy','Erupcja Wezuwiusza zasypała Pompeje.'),
('hist_03','HISTORIA','Kto był pierwszym człowiekiem na Księżycu?','["Jurij Gagarin","Buzz Aldrin","Neil Armstrong","John Glenn"]',2,'easy','Neil Armstrong stanął na Księżycu 20 lipca 1969 roku.'),
('hist_04','HISTORIA','Które imperium zbudowało Koloseum w Rzymie?','["Bizantyjskie","Rzymskie","Osmańskie","Perskie"]',1,'easy','Koloseum powstało w czasach Cesarstwa Rzymskiego.'),
('hist_05','HISTORIA','Jak nazywał się statek, którym Karol Darwin odbył słynną podróż badawczą?','["Endeavour","Beagle","Victory","Santa Maria"]',1,'hard','Darwin podróżował na HMS Beagle.'),
('hist_06','HISTORIA','Które wydarzenie symbolicznie rozpoczęło rewolucję francuską w 1789 roku?','["Bitwa pod Waterloo","Zdobycie Bastylii","Koronacja Napoleona","Kongres wiedeński"]',1,'medium','Zdobycie Bastylii 14 lipca 1789 roku stało się symbolem początku rewolucji.'),

('science_01','NAUKA','Jaki pierwiastek chemiczny ma symbol O?','["Złoto","Tlen","Osm","Wodór"]',1,'easy','O to symbol tlenu.'),
('science_02','NAUKA','Ile planet ma Układ Słoneczny według współczesnej klasyfikacji?','["7","8","9","10"]',1,'easy','Od 2006 roku Pluton klasyfikowany jest jako planeta karłowata, więc planet jest 8.'),
('science_03','NAUKA','Który organ pompuje krew w ludzkim organizmie?','["Wątroba","Płuco","Serce","Trzustka"]',2,'easy','Krew pompuje serce.'),
('science_04','NAUKA','Jak nazywa się proces, w którym rośliny wykorzystują światło do wytwarzania związków organicznych?','["Fermentacja","Fotosynteza","Destylacja","Transpiracja"]',1,'easy','To fotosynteza.'),
('science_05','NAUKA','Która planeta jest znana z wyraźnego systemu pierścieni?','["Mars","Wenus","Saturn","Merkury"]',2,'easy','Najbardziej rozbudowany i widoczny system pierścieni ma Saturn.'),
('science_06','NAUKA','Jaką jednostką mierzy się natężenie prądu elektrycznego w układzie SI?','["Wolt","Wat","Amper","Om"]',2,'medium','Jednostką natężenia prądu jest amper.'),

('sport_01','SPORT','Ilu zawodników jednej drużyny przebywa na boisku na początku meczu piłki nożnej?','["9","10","11","12"]',2,'easy','Drużyna zaczyna mecz z 11 zawodnikami na boisku.'),
('sport_02','SPORT','W którym sporcie używa się lotki?','["Squash","Badminton","Tenis stołowy","Padel"]',1,'easy','Lotką gra się w badmintona.'),
('sport_03','SPORT','Ile punktów wart jest rzut zza linii za trzy punkty w koszykówce?','["1","2","3","4"]',2,'easy','Taki celny rzut daje 3 punkty.'),
('sport_04','SPORT','Jak nazywa się turniej tenisowy rozgrywany na trawiastych kortach w Londynie?','["Roland Garros","US Open","Wimbledon","Australian Open"]',2,'easy','Wimbledon rozgrywany jest na trawie.'),
('sport_05','SPORT','Który kolor koszulki nosi lider klasyfikacji generalnej Tour de France?','["Zielony","Żółty","Czerwony","Biały"]',1,'medium','Lider Tour de France jedzie w żółtej koszulce.'),
('sport_06','SPORT','Ile kół olimpijskich znajduje się w symbolu igrzysk?','["4","5","6","7"]',1,'easy','Symbol olimpijski składa się z 5 kół.'),

('food_01','JEDZENIE','Z jakiego kraju pochodzi paella?','["Włochy","Hiszpania","Portugalia","Meksyk"]',1,'easy','Paella wywodzi się z Hiszpanii, szczególnie z Walencji.'),
('food_02','JEDZENIE','Który składnik jest podstawą tradycyjnego hummusu?','["Soczewica","Ciecierzyca","Fasola","Groch"]',1,'easy','Podstawą hummusu jest ciecierzyca.'),
('food_03','JEDZENIE','Z jakiego mleka tradycyjnie produkuje się włoską mozzarellę di bufala?','["Krowiego","Koziego","Bawolego","Owczego"]',2,'medium','Mozzarella di bufala powstaje z mleka bawolego.'),
('food_04','JEDZENIE','Jak nazywa się japońska pasta z fermentowanej soi używana m.in. w zupie?','["Miso","Pesto","Tahini","Harissa"]',0,'medium','To pasta miso.'),
('food_05','JEDZENIE','Który owoc jest podstawą guacamole?','["Mango","Awokado","Limonka","Pomidor"]',1,'easy','Podstawą guacamole jest awokado.'),
('food_06','JEDZENIE','Jak nazywa się francuski deser z karmelizowaną warstwą cukru na wierzchu?','["Tiramisu","Crème brûlée","Panna cotta","Baklava"]',1,'easy','To crème brûlée.'),

('lang_01','JĘZYK','Który z tych języków należy do grupy języków romańskich?','["Fiński","Węgierski","Portugalski","Polski"]',2,'easy','Portugalski wywodzi się z łaciny i jest językiem romańskim.'),
('lang_02','JĘZYK','Co oznacza hiszpańskie słowo „gracias”?','["Proszę","Dziękuję","Przepraszam","Dzień dobry"]',1,'easy','„Gracias” znaczy „dziękuję”.'),
('lang_03','JĘZYK','Jak nazywa się alfabet używany współcześnie m.in. w języku rosyjskim?','["Cyrylica","Runy","Kanji","Devanagari"]',0,'easy','Rosyjski zapisuje się cyrylicą.'),
('lang_04','JĘZYK','Które słowo jest palindromem?','["kajak","rower","hotel","banan"]',0,'easy','„kajak” czyta się tak samo od lewej i od prawej.'),
('lang_05','JĘZYK','Jak brzmi liczba 3 po grecku w podstawowej formie liczebnika?','["tria","pente","deka","ena"]',0,'medium','Greckie „τρία” (tria) oznacza 3.'),
('lang_06','JĘZYK','Który znak kończy zdanie pytające w języku polskim?','["Dwukropek","Średnik","Znak zapytania","Apostrof"]',2,'easy','Zdanie pytające kończymy znakiem zapytania.'),

('pl_01','POLSKA','Jaka rzeka przepływa przez Warszawę?','["Odra","Wisła","Warta","Bug"]',1,'easy','Przez Warszawę przepływa Wisła.'),
('pl_02','POLSKA','Który polski kompozytor jest patronem międzynarodowego konkursu pianistycznego w Warszawie?','["Stanisław Moniuszko","Fryderyk Chopin","Krzysztof Penderecki","Henryk Wieniawski"]',1,'easy','To Międzynarodowy Konkurs Pianistyczny im. Fryderyka Chopina.'),
('pl_03','POLSKA','W jakim mieście znajduje się zamek na Wawelu?','["Gdańsk","Kraków","Poznań","Toruń"]',1,'easy','Wawel znajduje się w Krakowie.'),
('pl_04','POLSKA','Które morze leży na północ od Polski?','["Czarne","Północne","Bałtyckie","Adriatyckie"]',2,'easy','Polska ma dostęp do Morza Bałtyckiego.'),
('pl_05','POLSKA','Jak nazywa się najwyższy szczyt leżący na terytorium Polski?','["Giewont","Śnieżka","Rysy","Kasprowy Wierch"]',2,'easy','Najwyższym punktem Polski jest północno-zachodni wierzchołek Rysów.'),
('pl_06','POLSKA','Który astronom sformułował heliocentryczny model Układu Słonecznego i urodził się w Toruniu?','["Jan Heweliusz","Mikołaj Kopernik","Aleksander Wolszczan","Marian Rejewski"]',1,'easy','Chodzi o Mikołaja Kopernika.'),

('world_01','ŚWIAT','W którym państwie znajdują się piramidy w Gizie?','["Jordania","Egipt","Maroko","Tunezja"]',1,'easy','Piramidy w Gizie znajdują się w Egipcie.'),
('world_02','ŚWIAT','Jaką walutą posługuje się Japonia?','["Won","Jen","Juan","Ringgit"]',1,'easy','Walutą Japonii jest jen.'),
('world_03','ŚWIAT','W jakim mieście znajduje się Statua Wolności?','["Boston","Nowy Jork","Waszyngton","Filadelfia"]',1,'easy','Statua Wolności stoi w Nowym Jorku.'),
('world_04','ŚWIAT','Który kraj ma liść klonu na fladze?','["Kanada","Austria","Dania","Szwajcaria"]',0,'easy','Liść klonu jest symbolem Kanady.'),
('world_05','ŚWIAT','Na jakiej wyspie znajduje się państwo Islandia?','["Na Islandii","Na Grenlandii","Na Gotlandii","Na Sycylii"]',0,'easy','Państwo Islandia zajmuje wyspę Islandię i mniejsze wyspy.'),
('world_06','ŚWIAT','Który kanał łączy Morze Śródziemne z Morzem Czerwonym?','["Panamski","Kiloński","Sueski","Koryncki"]',2,'medium','Morza te łączy Kanał Sueski.'),

('pop_01','POP KULTURA','Jak nazywa się szkoła magii z serii o Harrym Potterze?','["Narnia","Hogwart","Nevermore","Camelot"]',1,'easy','Harry Potter uczy się w Hogwarcie.'),
('pop_02','POP KULTURA','Który superbohater jest alter ego Bruce’a Wayne’a?','["Superman","Batman","Iron Man","Spider-Man"]',1,'easy','Bruce Wayne to Batman.'),
('pop_03','POP KULTURA','Jak nazywa się żółta rodzina z animowanego serialu mieszkająca w Springfield?','["Griffinowie","Simpsonowie","Flintstonowie","Jetsonowie"]',1,'easy','Chodzi o Simpsonów.'),
('pop_04','POP KULTURA','Która postać z „Gwiezdnych wojen” mówi charakterystycznym szykiem przestawnym?','["Han Solo","Yoda","Chewbacca","C-3PO"]',1,'easy','Charakterystycznie mówi mistrz Yoda.'),
('pop_05','POP KULTURA','Jak nazywa się fikcyjny kontynent, na którym leży Królewska Przystań w „Grze o tron”?','["Westeros","Pandora","Tamriel","Azeroth"]',0,'medium','Królewska Przystań leży w Westeros.'),
('pop_06','POP KULTURA','Która gra planszowa polega na kupowaniu ulic i pobieraniu czynszu?','["Scrabble","Monopoly","Cluedo","Risk"]',1,'easy','Chodzi o Monopoly.'),

('tech_01','TECHNOLOGIA','Co oznacza skrót GPS?','["Global Positioning System","General Processing Service","Global Phone Signal","Graphic Positioning Standard"]',0,'medium','GPS to Global Positioning System.'),
('tech_02','TECHNOLOGIA','Która firma stworzyła system operacyjny Android i rozwija go jako główny opiekun projektu?','["Apple","Google","IBM","Adobe"]',1,'easy','Android jest rozwijany pod kierunkiem Google.'),
('tech_03','TECHNOLOGIA','Ile bitów składa się na 1 bajt?','["4","8","16","32"]',1,'easy','1 bajt to 8 bitów.'),
('tech_04','TECHNOLOGIA','Jak nazywa się protokół używany w adresie bezpiecznej strony internetowej, zwykle widoczny jako „https”?','["HTTPS","FTP","SMTP","Bluetooth"]',0,'easy','HTTPS to szyfrowany wariant protokołu HTTP.'),
('tech_05','TECHNOLOGIA','Co w komputerze przechowuje dane robocze krótkotrwale i traci je po wyłączeniu zasilania?','["SSD","RAM","Pendrive","Blu-ray"]',1,'medium','Pamięć RAM jest pamięcią ulotną.'),
('tech_06','TECHNOLOGIA','Który format pliku jest standardowo kojarzony z dokumentem przenośnym zachowującym układ stron?','["PDF","MP3","PNG","CSV"]',0,'easy','PDF oznacza Portable Document Format.')
on conflict (question_key) do update set
  category=excluded.category,
  prompt=excluded.prompt,
  options=excluded.options,
  correct_index=excluded.correct_index,
  difficulty=excluded.difficulty,
  explanation=excluded.explanation;

create or replace function app_private.va_banque_choose_question_internal(
  p_room_id uuid,
  p_exclude_category text default null
)
returns bigint
language plpgsql
security definer
set search_path = app_private, pg_temp
as $$
declare
  v_used bigint[];
  v_id bigint;
begin
  select used_question_ids into v_used
  from app_private.va_banque_games
  where room_id=p_room_id;

  select q.id into v_id
  from app_private.va_banque_questions q
  where not (q.id = any(coalesce(v_used,'{}'::bigint[])))
    and (p_exclude_category is null or q.category <> p_exclude_category)
  order by random()
  limit 1;

  if v_id is null then
    select q.id into v_id
    from app_private.va_banque_questions q
    where not (q.id = any(coalesce(v_used,'{}'::bigint[])))
    order by random()
    limit 1;
  end if;

  if v_id is null then
    raise exception 'Question bank exhausted';
  end if;

  update app_private.va_banque_games
  set used_question_ids=array_append(used_question_ids,v_id), updated_at=now()
  where room_id=p_room_id;

  return v_id;
end;
$$;

create or replace function app_private.initialize_va_banque_internal(p_room_id uuid)
returns boolean
language plpgsql
security definer
set search_path = app_private, pg_temp
as $$
declare
  v_count integer;
  v_rounds integer;
  v_question bigint;
begin
  select count(*) into v_count
  from app_private.room_players
  where room_id=p_room_id;

  if v_count < 2 or v_count > 8 then
    return false;
  end if;

  delete from app_private.va_banque_players where room_id=p_room_id;
  delete from app_private.va_banque_games where room_id=p_room_id;

  v_rounds := case
    when v_count <= 3 then 10
    when v_count <= 5 then 9
    else 8
  end;

  insert into app_private.va_banque_games(
    room_id,round_index,regular_rounds,phase,phase_deadline
  )
  values(p_room_id,1,v_rounds,'intro',now()+interval '8 seconds');

  insert into app_private.va_banque_players(room_id,player_id,points)
  select p_room_id,p.id,2000
  from app_private.room_players p
  where p.room_id=p_room_id;

  v_question := app_private.va_banque_choose_question_internal(p_room_id,null);

  update app_private.va_banque_games
  set question_id=v_question
  where room_id=p_room_id;

  return true;
end;
$$;

create or replace function app_private.va_banque_reset_round_players_internal(p_room_id uuid)
returns void
language sql
security definer
set search_path = app_private, pg_temp
as $$
  update app_private.va_banque_players
  set bid=null,bid_locked=false,tie_bid=null,tie_locked=false,
      answer_index=null,answer_locked=false
  where room_id=p_room_id;
$$;

create or replace function app_private.va_banque_advance_round_internal(p_room_id uuid)
returns void
language plpgsql
security definer
set search_path = app_private, pg_temp
as $$
declare
  g app_private.va_banque_games%rowtype;
  q_category text;
  next_q bigint;
begin
  select * into g from app_private.va_banque_games where room_id=p_room_id for update;
  if g.room_id is null then return; end if;

  select category into q_category
  from app_private.va_banque_questions
  where id=g.question_id;

  if g.round_index >= g.regular_rounds then
    next_q := app_private.va_banque_choose_question_internal(p_room_id,q_category);

    update app_private.va_banque_players
    set final_bid=null,final_bid_locked=false,
        final_answer_index=null,final_answer_locked=false
    where room_id=p_room_id;

    update app_private.va_banque_games
    set phase='final_category',
        phase_deadline=now()+interval '4 seconds',
        previous_category=q_category,
        question_id=next_q,
        winning_player_id=null,
        winning_bid=null,
        tie_player_ids='{}',
        takeover_player_id=null,
        takeover_risk=null,
        last_event=jsonb_build_object('type','final_category'),
        updated_at=now()
    where room_id=p_room_id;
    return;
  end if;

  next_q := app_private.va_banque_choose_question_internal(p_room_id,q_category);
  perform app_private.va_banque_reset_round_players_internal(p_room_id);

  update app_private.va_banque_games
  set round_index=round_index+1,
      phase='category',
      phase_deadline=now()+interval '3 seconds',
      previous_category=q_category,
      question_id=next_q,
      winning_player_id=null,
      winning_bid=null,
      tie_player_ids='{}',
      takeover_player_id=null,
      takeover_risk=null,
      last_event=jsonb_build_object('type','new_round'),
      updated_at=now()
  where room_id=p_room_id;
end;
$$;

create or replace function app_private.va_banque_tick_internal(p_code text)
returns void
language plpgsql
security definer
set search_path = app_private, pg_temp
as $$
declare
  r app_private.platform_rooms%rowtype;
  g app_private.va_banque_games%rowtype;
  q app_private.va_banque_questions%rowtype;
  v_count integer;
  v_locked integer;
  v_max integer;
  v_tied uuid[];
  v_winner uuid;
  v_correct boolean;
  v_answer smallint;
  v_delta integer;
  v_risk integer;
  v_loop integer := 0;
begin
  select * into r
  from app_private.platform_rooms
  where code=upper(trim(p_code))
    and game_slug='va-banque'
    and status='active'
    and expires_at>now()
  limit 1;

  if r.id is null then return; end if;

  loop
    v_loop := v_loop+1;
    exit when v_loop > 12;

    select * into g
    from app_private.va_banque_games
    where room_id=r.id
    for update;

    exit when g.room_id is null or g.phase='finished';

    select * into q
    from app_private.va_banque_questions
    where id=g.question_id;

    select count(*) into v_count
    from app_private.va_banque_players
    where room_id=r.id;

    if g.phase='intro' then
      exit when g.phase_deadline>now();
      update app_private.va_banque_games
      set phase='category',phase_deadline=now()+interval '3 seconds',
          last_event=jsonb_build_object('type','category'),updated_at=now()
      where room_id=r.id;
      continue;
    end if;

    if g.phase='category' then
      exit when g.phase_deadline>now();
      perform app_private.va_banque_reset_round_players_internal(r.id);
      update app_private.va_banque_games
      set phase='bidding',phase_deadline=now()+interval '12 seconds',
          last_event=jsonb_build_object('type','bidding_started'),updated_at=now()
      where room_id=r.id;
      continue;
    end if;

    if g.phase='bidding' then
      select count(*) into v_locked
      from app_private.va_banque_players
      where room_id=r.id and bid_locked;

      exit when g.phase_deadline>now() and v_locked<v_count;

      update app_private.va_banque_players
      set bid=coalesce(bid,0),bid_locked=true
      where room_id=r.id and not bid_locked;

      select coalesce(max(bid),0) into v_max
      from app_private.va_banque_players
      where room_id=r.id;

      if v_max<=0 then
        update app_private.va_banque_games
        set phase='round_result',phase_deadline=now()+interval '3 seconds',
            last_event=jsonb_build_object('type','all_pass'),updated_at=now()
        where room_id=r.id;
        continue;
      end if;

      select array_agg(player_id order by player_id) into v_tied
      from app_private.va_banque_players
      where room_id=r.id and bid=v_max;

      if coalesce(array_length(v_tied,1),0)=1 then
        v_winner:=v_tied[1];
        update app_private.va_banque_games
        set winning_player_id=v_winner,winning_bid=v_max,
            tie_player_ids='{}',phase='bid_reveal',
            phase_deadline=now()+interval '3 seconds',
            last_event=jsonb_build_object('type','bid_won','playerId',v_winner,'bid',v_max),
            updated_at=now()
        where room_id=r.id;
        continue;
      end if;

      update app_private.va_banque_players
      set tie_bid=null,tie_locked=false
      where room_id=r.id and player_id=any(v_tied);

      update app_private.va_banque_games
      set winning_bid=v_max,tie_player_ids=v_tied,
          phase='tie_bid',phase_deadline=now()+interval '7 seconds',
          last_event=jsonb_build_object('type','bid_tie','bid',v_max,'players',to_jsonb(v_tied)),
          updated_at=now()
      where room_id=r.id;
      continue;
    end if;

    if g.phase='tie_bid' then
      select count(*) into v_locked
      from app_private.va_banque_players
      where room_id=r.id
        and player_id=any(g.tie_player_ids)
        and tie_locked;

      exit when g.phase_deadline>now()
        and v_locked<coalesce(array_length(g.tie_player_ids,1),0);

      update app_private.va_banque_players
      set tie_bid=coalesce(tie_bid,0),tie_locked=true
      where room_id=r.id
        and player_id=any(g.tie_player_ids)
        and not tie_locked;

      select coalesce(max(tie_bid),0) into v_max
      from app_private.va_banque_players
      where room_id=r.id and player_id=any(g.tie_player_ids);

      if v_max<=0 then
        select x into v_winner
        from unnest(g.tie_player_ids) x
        order by random()
        limit 1;
        v_max:=g.winning_bid;
      else
        select player_id into v_winner
        from app_private.va_banque_players
        where room_id=r.id
          and player_id=any(g.tie_player_ids)
          and tie_bid=v_max
        order by random()
        limit 1;
      end if;

      update app_private.va_banque_games
      set winning_player_id=v_winner,winning_bid=v_max,
          phase='tie_reveal',phase_deadline=now()+interval '2 seconds',
          last_event=jsonb_build_object('type','tie_won','playerId',v_winner,'bid',v_max),
          updated_at=now()
      where room_id=r.id;
      continue;
    end if;

    if g.phase in ('bid_reveal','tie_reveal') then
      exit when g.phase_deadline>now();
      update app_private.va_banque_games
      set phase='question',phase_deadline=now()+interval '18 seconds',
          last_event=jsonb_build_object('type','question_started'),
          updated_at=now()
      where room_id=r.id;
      continue;
    end if;

    if g.phase='question' then
      select answer_index,answer_locked into v_answer,v_correct
      from app_private.va_banque_players
      where room_id=r.id and player_id=g.winning_player_id;

      -- v_correct temporarily carries answer_locked.
      exit when g.phase_deadline>now() and not coalesce(v_correct,false);

      if v_answer is null then
        v_correct:=false;
      else
        v_correct:=(v_answer=q.correct_index);
      end if;

      if v_correct then
        update app_private.va_banque_players
        set points=points+g.winning_bid
        where room_id=r.id and player_id=g.winning_player_id;
        v_delta:=g.winning_bid;
      else
        update app_private.va_banque_players
        set points=greatest(100,points-g.winning_bid)
        where room_id=r.id and player_id=g.winning_player_id;
        v_delta:=-g.winning_bid;
      end if;

      update app_private.va_banque_games
      set phase='main_result',phase_deadline=now()+interval '3 seconds',
          last_event=jsonb_build_object(
            'type',case when v_correct then 'main_correct' else 'main_wrong' end,
            'playerId',g.winning_player_id,'delta',v_delta,'answer',v_answer,
            'correctIndex',q.correct_index
          ),
          updated_at=now()
      where room_id=r.id;
      continue;
    end if;

    if g.phase='main_result' then
      exit when g.phase_deadline>now();

      if g.last_event->>'type'='main_correct' then
        update app_private.va_banque_games
        set phase='round_result',phase_deadline=now()+interval '2 seconds',updated_at=now()
        where room_id=r.id;
      else
        update app_private.va_banque_games
        set phase='takeover_open',phase_deadline=now()+interval '4 seconds',
            takeover_player_id=null,takeover_risk=null,
            last_event=jsonb_build_object('type','takeover_open'),
            updated_at=now()
        where room_id=r.id;
      end if;
      continue;
    end if;

    if g.phase='takeover_open' then
      exit when g.phase_deadline>now();
      update app_private.va_banque_games
      set phase='round_result',phase_deadline=now()+interval '2 seconds',
          last_event=jsonb_build_object('type','no_takeover'),
          updated_at=now()
      where room_id=r.id;
      continue;
    end if;

    if g.phase='takeover_question' then
      select answer_index,answer_locked into v_answer,v_correct
      from app_private.va_banque_players
      where room_id=r.id and player_id=g.takeover_player_id;

      exit when g.phase_deadline>now() and not coalesce(v_correct,false);

      v_correct:=(v_answer is not null and v_answer=q.correct_index);
      v_risk:=coalesce(g.takeover_risk,0);

      if v_correct then
        update app_private.va_banque_players
        set points=points+v_risk
        where room_id=r.id and player_id=g.takeover_player_id;
        v_delta:=v_risk;
      else
        update app_private.va_banque_players
        set points=greatest(100,points-v_risk)
        where room_id=r.id and player_id=g.takeover_player_id;
        v_delta:=-v_risk;
      end if;

      update app_private.va_banque_games
      set phase='takeover_result',phase_deadline=now()+interval '3 seconds',
          last_event=jsonb_build_object(
            'type',case when v_correct then 'takeover_correct' else 'takeover_wrong' end,
            'playerId',g.takeover_player_id,'delta',v_delta,'answer',v_answer,
            'correctIndex',q.correct_index
          ),
          updated_at=now()
      where room_id=r.id;
      continue;
    end if;

    if g.phase='takeover_result' then
      exit when g.phase_deadline>now();
      update app_private.va_banque_games
      set phase='round_result',phase_deadline=now()+interval '2 seconds',updated_at=now()
      where room_id=r.id;
      continue;
    end if;

    if g.phase='round_result' then
      exit when g.phase_deadline>now();
      perform app_private.va_banque_advance_round_internal(r.id);
      continue;
    end if;

    if g.phase='final_category' then
      exit when g.phase_deadline>now();
      update app_private.va_banque_players
      set final_bid=null,final_bid_locked=false,
          final_answer_index=null,final_answer_locked=false
      where room_id=r.id;

      update app_private.va_banque_games
      set phase='final_bidding',phase_deadline=now()+interval '15 seconds',
          last_event=jsonb_build_object('type','final_bidding'),
          updated_at=now()
      where room_id=r.id;
      continue;
    end if;

    if g.phase='final_bidding' then
      select count(*) into v_locked
      from app_private.va_banque_players
      where room_id=r.id and final_bid_locked;

      exit when g.phase_deadline>now() and v_locked<v_count;

      update app_private.va_banque_players
      set final_bid=coalesce(final_bid,0),final_bid_locked=true
      where room_id=r.id and not final_bid_locked;

      update app_private.va_banque_games
      set phase='final_question',phase_deadline=now()+interval '20 seconds',
          last_event=jsonb_build_object('type','final_question'),
          updated_at=now()
      where room_id=r.id;
      continue;
    end if;

    if g.phase='final_question' then
      select count(*) into v_locked
      from app_private.va_banque_players
      where room_id=r.id and final_answer_locked;

      exit when g.phase_deadline>now() and v_locked<v_count;

      update app_private.va_banque_players
      set points=case
        when final_answer_locked and final_answer_index=q.correct_index
          then points+coalesce(final_bid,0)
        else greatest(0,points-coalesce(final_bid,0))
      end
      where room_id=r.id;

      update app_private.va_banque_games
      set phase='final_reveal',phase_deadline=now()+interval '6 seconds',
          last_event=jsonb_build_object('type','final_reveal','correctIndex',q.correct_index),
          updated_at=now()
      where room_id=r.id;
      continue;
    end if;

    if g.phase='final_reveal' then
      exit when g.phase_deadline>now();
      update app_private.va_banque_games
      set phase='finished',phase_deadline=now(),
          last_event=jsonb_build_object('type','finished'),updated_at=now()
      where room_id=r.id;

      update app_private.platform_rooms
      set game_phase='finished'
      where id=r.id;
      continue;
    end if;

    exit;
  end loop;
end;
$$;

create or replace function app_private.get_va_banque_state_internal(
  p_code text,
  p_player_token uuid default null,
  p_host_token uuid default null
)
returns jsonb
language plpgsql
security definer
set search_path = app_private, pg_temp
as $$
declare
  r app_private.platform_rooms%rowtype;
  g app_private.va_banque_games%rowtype;
  q app_private.va_banque_questions%rowtype;
  viewer app_private.room_players%rowtype;
  vp app_private.va_banque_players%rowtype;
  v_players jsonb;
  v_bids jsonb;
  v_final_answers jsonb;
  v_show_question boolean;
  v_show_solution boolean;
  v_is_host boolean := false;
begin
  perform app_private.va_banque_tick_internal(p_code);

  select * into r
  from app_private.platform_rooms
  where code=upper(trim(p_code))
    and game_slug='va-banque'
    and status='active'
    and expires_at>now()
  limit 1;

  if r.id is null then return null; end if;

  v_is_host := p_host_token is not null and r.host_token=p_host_token;

  if p_player_token is not null then
    select * into viewer
    from app_private.room_players
    where room_id=r.id and player_token=p_player_token
    limit 1;

    if viewer.id is null then
      raise exception 'Player not found';
    end if;

    update app_private.room_players
    set last_seen_at=now()
    where id=viewer.id;

    select * into vp
    from app_private.va_banque_players
    where room_id=r.id and player_id=viewer.id;
  elsif not v_is_host then
    raise exception 'Access denied';
  end if;

  select * into g from app_private.va_banque_games where room_id=r.id;
  select * into q from app_private.va_banque_questions where id=g.question_id;

  v_show_question := g.phase in (
    'question','main_result','takeover_open','takeover_question',
    'takeover_result','round_result','final_question','final_reveal','finished'
  );
  v_show_solution := g.phase in (
    'main_result','takeover_open','takeover_result','round_result','final_reveal','finished'
  );

  select jsonb_agg(
    jsonb_build_object(
      'id',p.id,
      'name',rp.display_name,
      'avatar',rp.avatar,
      'points',p.points,
      'isConnected',rp.last_seen_at > now()-interval '12 seconds'
    )
    order by p.points desc,rp.joined_at asc
  ) into v_players
  from app_private.va_banque_players p
  join app_private.room_players rp on rp.id=p.player_id
  where p.room_id=r.id;

  if g.phase in ('bid_reveal','tie_bid','tie_reveal','question','main_result','takeover_open','takeover_question','takeover_result','round_result') then
    select jsonb_agg(
      jsonb_build_object(
        'playerId',p.player_id,
        'bid',p.bid,
        'tieBid',case when p.tie_locked then p.tie_bid else null end
      )
      order by rp.joined_at
    ) into v_bids
    from app_private.va_banque_players p
    join app_private.room_players rp on rp.id=p.player_id
    where p.room_id=r.id;
  else
    v_bids:='[]'::jsonb;
  end if;

  if g.phase in ('final_reveal','finished') then
    select jsonb_agg(
      jsonb_build_object(
        'playerId',p.player_id,
        'bid',p.final_bid,
        'answerIndex',p.final_answer_index,
        'correct',p.final_answer_index=q.correct_index
      )
      order by rp.joined_at
    ) into v_final_answers
    from app_private.va_banque_players p
    join app_private.room_players rp on rp.id=p.player_id
    where p.room_id=r.id;
  else
    v_final_answers:='[]'::jsonb;
  end if;

  return jsonb_build_object(
    'serverNow',now(),
    'phase',g.phase,
    'deadline',g.phase_deadline,
    'roundIndex',g.round_index,
    'regularRounds',g.regular_rounds,
    'category',q.category,
    'difficulty',q.difficulty,
    'question',case when v_show_question then q.prompt else null end,
    'options',case when v_show_question then q.options else '[]'::jsonb end,
    'correctIndex',case when v_show_solution then q.correct_index else null end,
    'explanation',case when v_show_solution then q.explanation else null end,
    'players',coalesce(v_players,'[]'::jsonb),
    'bids',coalesce(v_bids,'[]'::jsonb),
    'winningPlayerId',g.winning_player_id,
    'winningBid',g.winning_bid,
    'tiePlayerIds',to_jsonb(g.tie_player_ids),
    'takeoverPlayerId',g.takeover_player_id,
    'takeoverRisk',g.takeover_risk,
    'lastEvent',g.last_event,
    'finalAnswers',coalesce(v_final_answers,'[]'::jsonb),
    'isHost',v_is_host,
    'viewer',case when viewer.id is null then null else jsonb_build_object(
      'id',viewer.id,
      'name',viewer.display_name,
      'avatar',viewer.avatar,
      'points',vp.points,
      'bid',vp.bid,
      'bidLocked',vp.bid_locked,
      'tieBid',vp.tie_bid,
      'tieLocked',vp.tie_locked,
      'answerIndex',vp.answer_index,
      'answerLocked',vp.answer_locked,
      'finalBid',vp.final_bid,
      'finalBidLocked',vp.final_bid_locked,
      'finalAnswerIndex',vp.final_answer_index,
      'finalAnswerLocked',vp.final_answer_locked
    ) end
  );
end;
$$;

create or replace function app_private.submit_va_banque_bid_internal(
  p_code text,p_player_token uuid,p_bid integer
)
returns boolean
language plpgsql
security definer
set search_path = app_private, pg_temp
as $$
declare
  r app_private.platform_rooms%rowtype;
  g app_private.va_banque_games%rowtype;
  p app_private.va_banque_players%rowtype;
  v_max integer;
  v_min integer;
begin
  perform app_private.va_banque_tick_internal(p_code);

  select * into r from app_private.platform_rooms
  where code=upper(trim(p_code)) and game_slug='va-banque' and status='active' limit 1;
  if r.id is null then raise exception 'Game not found'; end if;

  select * into g from app_private.va_banque_games where room_id=r.id for update;
  if g.phase<>'bidding' or g.phase_deadline<=now() then raise exception 'Bidding closed'; end if;

  select vp.* into p
  from app_private.va_banque_players vp
  join app_private.room_players rp on rp.id=vp.player_id
  where vp.room_id=r.id and rp.player_token=p_player_token
  for update of vp;

  if p.player_id is null then raise exception 'Player not found'; end if;
  if p.bid_locked then raise exception 'Bid already locked'; end if;

  v_max:=greatest(50,floor((p.points*0.5)/50.0)::integer*50);
  v_min:=least(100,v_max);

  if p_bid<>0 and (p_bid<v_min or p_bid>v_max or p_bid%50<>0) then
    raise exception 'Invalid bid';
  end if;

  update app_private.va_banque_players
  set bid=p_bid,bid_locked=true
  where room_id=r.id and player_id=p.player_id;

  perform app_private.va_banque_tick_internal(p_code);
  return true;
end;
$$;

create or replace function app_private.submit_va_banque_tie_bid_internal(
  p_code text,p_player_token uuid,p_bid integer
)
returns boolean
language plpgsql
security definer
set search_path = app_private, pg_temp
as $$
declare
  r app_private.platform_rooms%rowtype;
  g app_private.va_banque_games%rowtype;
  p app_private.va_banque_players%rowtype;
  v_max integer;
  v_min integer;
begin
  perform app_private.va_banque_tick_internal(p_code);
  select * into r from app_private.platform_rooms
  where code=upper(trim(p_code)) and game_slug='va-banque' and status='active' limit 1;
  select * into g from app_private.va_banque_games where room_id=r.id for update;

  if g.phase<>'tie_bid' or g.phase_deadline<=now() then raise exception 'Tie bidding closed'; end if;

  select vp.* into p
  from app_private.va_banque_players vp
  join app_private.room_players rp on rp.id=vp.player_id
  where vp.room_id=r.id and rp.player_token=p_player_token
  for update of vp;

  if p.player_id is null or not (p.player_id=any(g.tie_player_ids)) then
    raise exception 'Not in tie';
  end if;
  if p.tie_locked then raise exception 'Bid already locked'; end if;

  v_max:=greatest(50,floor((p.points*0.5)/50.0)::integer*50);
  v_min:=g.winning_bid+50;

  if p_bid<>0 and (p_bid<v_min or p_bid>v_max or p_bid%50<>0) then
    raise exception 'Invalid tie bid';
  end if;

  update app_private.va_banque_players
  set tie_bid=p_bid,tie_locked=true
  where room_id=r.id and player_id=p.player_id;

  perform app_private.va_banque_tick_internal(p_code);
  return true;
end;
$$;

create or replace function app_private.submit_va_banque_answer_internal(
  p_code text,p_player_token uuid,p_answer_index smallint
)
returns boolean
language plpgsql
security definer
set search_path = app_private, pg_temp
as $$
declare
  r app_private.platform_rooms%rowtype;
  g app_private.va_banque_games%rowtype;
  v_player uuid;
begin
  if p_answer_index not between 0 and 3 then raise exception 'Invalid answer'; end if;
  perform app_private.va_banque_tick_internal(p_code);

  select * into r from app_private.platform_rooms
  where code=upper(trim(p_code)) and game_slug='va-banque' and status='active' limit 1;
  select * into g from app_private.va_banque_games where room_id=r.id for update;

  select rp.id into v_player
  from app_private.room_players rp
  where rp.room_id=r.id and rp.player_token=p_player_token
  limit 1;

  if v_player is null then raise exception 'Player not found'; end if;

  if g.phase='question' and v_player=g.winning_player_id then
    update app_private.va_banque_players
    set answer_index=p_answer_index,answer_locked=true
    where room_id=r.id and player_id=v_player and not answer_locked;
    if not found then raise exception 'Answer already locked'; end if;
  elsif g.phase='takeover_question' and v_player=g.takeover_player_id then
    update app_private.va_banque_players
    set answer_index=p_answer_index,answer_locked=true
    where room_id=r.id and player_id=v_player and not answer_locked;
    if not found then raise exception 'Answer already locked'; end if;
  else
    raise exception 'Not your question';
  end if;

  perform app_private.va_banque_tick_internal(p_code);
  return true;
end;
$$;

create or replace function app_private.claim_va_banque_takeover_internal(
  p_code text,p_player_token uuid
)
returns jsonb
language plpgsql
security definer
set search_path = app_private, pg_temp
as $$
declare
  r app_private.platform_rooms%rowtype;
  g app_private.va_banque_games%rowtype;
  v_player uuid;
  v_points integer;
  v_risk integer;
begin
  perform app_private.va_banque_tick_internal(p_code);

  select * into r from app_private.platform_rooms
  where code=upper(trim(p_code)) and game_slug='va-banque' and status='active' limit 1;

  select * into g
  from app_private.va_banque_games
  where room_id=r.id
  for update;

  if g.phase<>'takeover_open' or g.phase_deadline<=now() or g.takeover_player_id is not null then
    return jsonb_build_object('won',false);
  end if;

  select rp.id,vp.points into v_player,v_points
  from app_private.room_players rp
  join app_private.va_banque_players vp on vp.player_id=rp.id and vp.room_id=r.id
  where rp.room_id=r.id and rp.player_token=p_player_token
  limit 1;

  if v_player is null or v_player=g.winning_player_id then
    return jsonb_build_object('won',false);
  end if;

  v_risk:=least(v_points,greatest(50,round((g.winning_bid*0.5)/50.0)::integer*50));

  update app_private.va_banque_players
  set answer_index=null,answer_locked=false
  where room_id=r.id and player_id=v_player;

  update app_private.va_banque_games
  set takeover_player_id=v_player,takeover_risk=v_risk,
      phase='takeover_question',phase_deadline=now()+interval '12 seconds',
      last_event=jsonb_build_object('type','takeover_claimed','playerId',v_player,'risk',v_risk),
      updated_at=now()
  where room_id=r.id;

  return jsonb_build_object('won',true,'risk',v_risk);
end;
$$;

create or replace function app_private.submit_va_banque_final_bid_internal(
  p_code text,p_player_token uuid,p_bid integer
)
returns boolean
language plpgsql
security definer
set search_path = app_private, pg_temp
as $$
declare
  r app_private.platform_rooms%rowtype;
  g app_private.va_banque_games%rowtype;
  v_player uuid;
  v_points integer;
begin
  perform app_private.va_banque_tick_internal(p_code);
  select * into r from app_private.platform_rooms
  where code=upper(trim(p_code)) and game_slug='va-banque' and status='active' limit 1;
  select * into g from app_private.va_banque_games where room_id=r.id for update;
  if g.phase<>'final_bidding' or g.phase_deadline<=now() then raise exception 'Final bidding closed'; end if;

  select rp.id,vp.points into v_player,v_points
  from app_private.room_players rp
  join app_private.va_banque_players vp on vp.player_id=rp.id and vp.room_id=r.id
  where rp.room_id=r.id and rp.player_token=p_player_token
  limit 1;

  if v_player is null then raise exception 'Player not found'; end if;
  if p_bid<0 or p_bid>v_points then raise exception 'Invalid final bid'; end if;

  update app_private.va_banque_players
  set final_bid=p_bid,final_bid_locked=true
  where room_id=r.id and player_id=v_player and not final_bid_locked;
  if not found then raise exception 'Bid already locked'; end if;

  perform app_private.va_banque_tick_internal(p_code);
  return true;
end;
$$;

create or replace function app_private.submit_va_banque_final_answer_internal(
  p_code text,p_player_token uuid,p_answer_index smallint
)
returns boolean
language plpgsql
security definer
set search_path = app_private, pg_temp
as $$
declare
  r app_private.platform_rooms%rowtype;
  g app_private.va_banque_games%rowtype;
  v_player uuid;
begin
  if p_answer_index not between 0 and 3 then raise exception 'Invalid answer'; end if;
  perform app_private.va_banque_tick_internal(p_code);

  select * into r from app_private.platform_rooms
  where code=upper(trim(p_code)) and game_slug='va-banque' and status='active' limit 1;
  select * into g from app_private.va_banque_games where room_id=r.id for update;
  if g.phase<>'final_question' or g.phase_deadline<=now() then raise exception 'Final answer closed'; end if;

  select id into v_player
  from app_private.room_players
  where room_id=r.id and player_token=p_player_token
  limit 1;
  if v_player is null then raise exception 'Player not found'; end if;

  update app_private.va_banque_players
  set final_answer_index=p_answer_index,final_answer_locked=true
  where room_id=r.id and player_id=v_player and not final_answer_locked;
  if not found then raise exception 'Answer already locked'; end if;

  perform app_private.va_banque_tick_internal(p_code);
  return true;
end;
$$;

create or replace function app_private.rematch_va_banque_internal(
  p_code text,p_host_token uuid
)
returns boolean
language plpgsql
security definer
set search_path = app_private, pg_temp
as $$
declare
  r app_private.platform_rooms%rowtype;
  g app_private.va_banque_games%rowtype;
begin
  select * into r
  from app_private.platform_rooms
  where code=upper(trim(p_code))
    and game_slug='va-banque'
    and host_token=p_host_token
    and status='active'
    and expires_at>now()
  limit 1;

  if r.id is null then return false; end if;
  select * into g from app_private.va_banque_games where room_id=r.id;
  if g.phase<>'finished' then return false; end if;

  if not app_private.initialize_va_banque_internal(r.id) then return false; end if;

  update app_private.platform_rooms
  set game_phase='playing'
  where id=r.id;

  return true;
end;
$$;

-- Extend the shared room allocator with VA BANQUE.
create or replace function app_private.create_platform_room_internal(p_game_slug text)
returns table (
  id uuid,
  code text,
  game_slug text,
  status text,
  host_token uuid,
  created_at timestamptz,
  expires_at timestamptz
)
language plpgsql
security definer
set search_path = app_private, pg_temp
as $$
declare
  alphabet constant text := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  generated_code text;
  inserted_room app_private.platform_rooms%rowtype;
  attempt integer;
begin
  if p_game_slug not in (
    'co-ludzie-powiedza','zakrecone-haslo','pod-przykrywka',
    'akta-nocy','tylko-my','va-banque'
  ) then
    raise exception 'Unsupported game';
  end if;

  for attempt in 1..20 loop
    select string_agg(
      substr(alphabet,1+floor(random()*length(alphabet))::integer,1),''
    )
    into generated_code
    from generate_series(1,4);

    begin
      insert into app_private.platform_rooms(code,game_slug)
      values(generated_code,p_game_slug)
      returning * into inserted_room;

      return query
      select inserted_room.id,inserted_room.code,inserted_room.game_slug,
             inserted_room.status,inserted_room.host_token,
             inserted_room.created_at,inserted_room.expires_at;
      return;
    exception when unique_violation then null;
    end;
  end loop;

  raise exception 'Could not allocate room code';
end;
$$;

create or replace function app_private.join_platform_room_internal(
  p_code text,p_display_name text,p_avatar text
)
returns table (
  id uuid,player_token uuid,display_name text,avatar text,team text,ready boolean
)
language plpgsql
security definer
set search_path = app_private, pg_temp
as $$
declare
  target_room app_private.platform_rooms%rowtype;
  inserted_player app_private.room_players%rowtype;
  player_count integer;
  room_limit integer;
  clean_name text := trim(p_display_name);
  alphabet constant text := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  generated_recovery text;
  attempt integer;
begin
  select * into target_room
  from app_private.platform_rooms
  where code=upper(trim(p_code)) and expires_at>now() and status='lobby'
  limit 1;

  if target_room.id is null then raise exception 'Room not found or not joinable'; end if;
  if char_length(clean_name)<1 or char_length(clean_name)>20 then raise exception 'Invalid name'; end if;

  if p_avatar not in (
    'avatar-01','avatar-02','avatar-03','avatar-04','avatar-05','avatar-06',
    'avatar-07','avatar-08','avatar-09','avatar-10','avatar-11','avatar-12',
    'avatar-13','avatar-14','avatar-15','avatar-16','avatar-17','avatar-18',
    'avatar-19','avatar-20','lion','fox','panda','tiger','koala','owl',
    'frog','penguin','bear','rabbit','monkey','cat'
  ) then raise exception 'Invalid avatar'; end if;

  room_limit:=case
    when target_room.game_slug='tylko-my' then 2
    when target_room.game_slug='va-banque' then 8
    when target_room.game_slug in ('zakrecone-haslo','akta-nocy') then 12
    else 14
  end;

  select count(*) into player_count
  from app_private.room_players where room_id=target_room.id;
  if player_count>=room_limit then raise exception 'Room is full'; end if;

  for attempt in 1..20 loop
    select string_agg(substr(alphabet,1+floor(random()*length(alphabet))::integer,1),'')
    into generated_recovery from generate_series(1,6);

    begin
      insert into app_private.room_players(room_id,display_name,avatar,recovery_code)
      values(target_room.id,clean_name,p_avatar,generated_recovery)
      returning * into inserted_player;

      return query
      select inserted_player.id,inserted_player.player_token,inserted_player.display_name,
             inserted_player.avatar,inserted_player.team,inserted_player.ready;
      return;
    exception when unique_violation then
      if exists(
        select 1 from app_private.room_players
        where room_id=target_room.id and lower(display_name)=lower(clean_name)
      ) then raise exception 'Name already taken'; end if;
    end;
  end loop;

  raise exception 'Could not allocate recovery code';
end;
$$;

create or replace function app_private.join_platform_room_account_internal(
  p_code text,p_display_name text,p_avatar text,p_partyplay_user_id uuid
)
returns table (
  id uuid,player_token uuid,display_name text,avatar text,team text,ready boolean
)
language plpgsql
security definer
set search_path = app_private, pg_temp
as $$
declare
  target_room app_private.platform_rooms%rowtype;
  inserted_player app_private.room_players%rowtype;
  player_count integer;
  room_limit integer;
  clean_name text := trim(p_display_name);
  alphabet constant text := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  generated_recovery text;
  attempt integer;
begin
  if p_partyplay_user_id is null then raise exception 'PartyPlay account required'; end if;

  select * into target_room
  from app_private.platform_rooms
  where code=upper(trim(p_code)) and expires_at>now() and status='lobby'
  limit 1;

  if target_room.id is null then raise exception 'Room not found or not joinable'; end if;
  if char_length(clean_name)<1 or char_length(clean_name)>20 then raise exception 'Invalid name'; end if;

  if p_avatar not in (
    'avatar-01','avatar-02','avatar-03','avatar-04','avatar-05',
    'avatar-06','avatar-07','avatar-08','avatar-09','avatar-10',
    'avatar-11','avatar-12','avatar-13','avatar-14','avatar-15',
    'avatar-16','avatar-17','avatar-18','avatar-19','avatar-20',
    'lion','fox','panda','tiger','koala','owl','frog','penguin','bear','rabbit','monkey','cat'
  ) then raise exception 'Invalid avatar'; end if;

  if exists(
    select 1 from app_private.room_players
    where room_id=target_room.id and partyplay_user_id=p_partyplay_user_id
  ) then raise exception 'PartyPlay account already joined'; end if;

  room_limit:=case
    when target_room.game_slug='tylko-my' then 2
    when target_room.game_slug='va-banque' then 8
    when target_room.game_slug in ('zakrecone-haslo','akta-nocy') then 12
    else 14
  end;

  select count(*) into player_count
  from app_private.room_players where room_id=target_room.id;
  if player_count>=room_limit then raise exception 'Room is full'; end if;

  for attempt in 1..20 loop
    select string_agg(substr(alphabet,1+floor(random()*length(alphabet))::integer,1),'')
    into generated_recovery from generate_series(1,6);

    begin
      insert into app_private.room_players(
        room_id,display_name,avatar,recovery_code,partyplay_user_id
      )
      values(target_room.id,clean_name,p_avatar,generated_recovery,p_partyplay_user_id)
      returning * into inserted_player;

      return query
      select inserted_player.id,inserted_player.player_token,inserted_player.display_name,
             inserted_player.avatar,inserted_player.team,inserted_player.ready;
      return;
    exception when unique_violation then
      if exists(
        select 1 from app_private.room_players
        where room_id=target_room.id and lower(display_name)=lower(clean_name)
      ) then raise exception 'Name already taken'; end if;
      if exists(
        select 1 from app_private.room_players
        where room_id=target_room.id and partyplay_user_id=p_partyplay_user_id
      ) then raise exception 'PartyPlay account already joined'; end if;
    end;
  end loop;

  raise exception 'Could not allocate recovery code';
end;
$$;

create or replace function app_private.start_platform_room_internal(
  p_code text,p_host_token uuid
)
returns boolean
language plpgsql
security definer
set search_path = app_private, pg_temp
as $$
declare
  target_room app_private.platform_rooms%rowtype;
  total_players integer;
  ready_players integer;
  unassigned_players integer;
  min_players integer;
  max_players integer;
begin
  select * into target_room
  from app_private.platform_rooms
  where code=upper(trim(p_code))
    and host_token=p_host_token
    and status='lobby'
    and expires_at>now()
  limit 1;

  if target_room.id is null then return false; end if;

  select count(*),count(*) filter(where ready),count(*) filter(where team is null)
  into total_players,ready_players,unassigned_players
  from app_private.room_players
  where room_id=target_room.id;

  if target_room.game_slug='va-banque' then
    if total_players<2 or total_players>8 or ready_players<>total_players then return false; end if;
    if not app_private.initialize_va_banque_internal(target_room.id) then
      raise exception 'Could not initialize VA BANQUE';
    end if;
    update app_private.platform_rooms
    set status='active',game_phase='playing'
    where id=target_room.id;
    return true;
  end if;

  if target_room.game_slug='tylko-my' then
    if total_players<>2 or ready_players<>total_players then return false; end if;
    if not app_private.initialize_tm_game_internal(target_room.id) then
      raise exception 'Could not initialize Tylko My';
    end if;
    update app_private.platform_rooms set status='active',game_phase='playing'
    where id=target_room.id;
    return true;
  end if;

  if target_room.game_slug='zakrecone-haslo' then
    if total_players<3 or total_players>12 or ready_players<>total_players then return false; end if;
    update app_private.platform_rooms set status='active',game_phase='playing'
    where id=target_room.id;
    if not app_private.initialize_zh_game_internal(target_room.id) then
      raise exception 'Could not initialize Zakrecone Haslo';
    end if;
    return true;
  end if;

  if target_room.game_slug='pod-przykrywka' then
    if total_players<6 or total_players>14 or ready_players<>total_players then return false; end if;
    update app_private.platform_rooms set status='active',game_phase='briefing'
    where id=target_room.id;
    if not app_private.initialize_pp_game_internal(target_room.id) then
      raise exception 'Could not initialize Pod Przykrywka';
    end if;
    return true;
  end if;

  if target_room.game_slug='akta-nocy' then
    if total_players<5 or total_players>12 or ready_players<>total_players then return false; end if;
    if not app_private.initialize_akta_nocy_internal(target_room.id) then
      raise exception 'Could not initialize Akta Nocy';
    end if;
    update app_private.platform_rooms set status='active',game_phase='akta_osobowe'
    where id=target_room.id;
    return true;
  end if;

  if total_players<4 or ready_players<>total_players or unassigned_players>0 then return false; end if;

  update app_private.platform_rooms
  set status='active',
      game_phase=case when target_room.game_slug='co-ludzie-powiedza'
                      then 'poznajmy_tlum' else game_phase end
  where id=target_room.id;
  return true;
end;
$$;

create or replace function public.get_va_banque_state(
  p_code text,p_player_token uuid default null,p_host_token uuid default null
)
returns jsonb
language sql
security invoker
set search_path = public, app_private, pg_temp
as $$
  select app_private.get_va_banque_state_internal(p_code,p_player_token,p_host_token);
$$;

create or replace function public.submit_va_banque_bid(
  p_code text,p_player_token uuid,p_bid integer
)
returns boolean
language sql
security invoker
set search_path = public, app_private, pg_temp
as $$
  select app_private.submit_va_banque_bid_internal(p_code,p_player_token,p_bid);
$$;

create or replace function public.submit_va_banque_tie_bid(
  p_code text,p_player_token uuid,p_bid integer
)
returns boolean
language sql
security invoker
set search_path = public, app_private, pg_temp
as $$
  select app_private.submit_va_banque_tie_bid_internal(p_code,p_player_token,p_bid);
$$;

create or replace function public.submit_va_banque_answer(
  p_code text,p_player_token uuid,p_answer_index smallint
)
returns boolean
language sql
security invoker
set search_path = public, app_private, pg_temp
as $$
  select app_private.submit_va_banque_answer_internal(p_code,p_player_token,p_answer_index);
$$;

create or replace function public.claim_va_banque_takeover(
  p_code text,p_player_token uuid
)
returns jsonb
language sql
security invoker
set search_path = public, app_private, pg_temp
as $$
  select app_private.claim_va_banque_takeover_internal(p_code,p_player_token);
$$;

create or replace function public.submit_va_banque_final_bid(
  p_code text,p_player_token uuid,p_bid integer
)
returns boolean
language sql
security invoker
set search_path = public, app_private, pg_temp
as $$
  select app_private.submit_va_banque_final_bid_internal(p_code,p_player_token,p_bid);
$$;

create or replace function public.submit_va_banque_final_answer(
  p_code text,p_player_token uuid,p_answer_index smallint
)
returns boolean
language sql
security invoker
set search_path = public, app_private, pg_temp
as $$
  select app_private.submit_va_banque_final_answer_internal(p_code,p_player_token,p_answer_index);
$$;

create or replace function public.rematch_va_banque(
  p_code text,p_host_token uuid
)
returns boolean
language sql
security invoker
set search_path = public, app_private, pg_temp
as $$
  select app_private.rematch_va_banque_internal(p_code,p_host_token);
$$;

revoke all on function public.get_va_banque_state(text,uuid,uuid) from public;
revoke all on function public.submit_va_banque_bid(text,uuid,integer) from public;
revoke all on function public.submit_va_banque_tie_bid(text,uuid,integer) from public;
revoke all on function public.submit_va_banque_answer(text,uuid,smallint) from public;
revoke all on function public.claim_va_banque_takeover(text,uuid) from public;
revoke all on function public.submit_va_banque_final_bid(text,uuid,integer) from public;
revoke all on function public.submit_va_banque_final_answer(text,uuid,smallint) from public;
revoke all on function public.rematch_va_banque(text,uuid) from public;

grant execute on function app_private.get_va_banque_state_internal(text,uuid,uuid) to anon,authenticated;
grant execute on function app_private.submit_va_banque_bid_internal(text,uuid,integer) to anon,authenticated;
grant execute on function app_private.submit_va_banque_tie_bid_internal(text,uuid,integer) to anon,authenticated;
grant execute on function app_private.submit_va_banque_answer_internal(text,uuid,smallint) to anon,authenticated;
grant execute on function app_private.claim_va_banque_takeover_internal(text,uuid) to anon,authenticated;
grant execute on function app_private.submit_va_banque_final_bid_internal(text,uuid,integer) to anon,authenticated;
grant execute on function app_private.submit_va_banque_final_answer_internal(text,uuid,smallint) to anon,authenticated;
grant execute on function app_private.rematch_va_banque_internal(text,uuid) to anon,authenticated;

grant execute on function public.get_va_banque_state(text,uuid,uuid) to anon,authenticated;
grant execute on function public.submit_va_banque_bid(text,uuid,integer) to anon,authenticated;
grant execute on function public.submit_va_banque_tie_bid(text,uuid,integer) to anon,authenticated;
grant execute on function public.submit_va_banque_answer(text,uuid,smallint) to anon,authenticated;
grant execute on function public.claim_va_banque_takeover(text,uuid) to anon,authenticated;
grant execute on function public.submit_va_banque_final_bid(text,uuid,integer) to anon,authenticated;
grant execute on function public.submit_va_banque_final_answer(text,uuid,smallint) to anon,authenticated;
grant execute on function public.rematch_va_banque(text,uuid) to anon,authenticated;
