-- III.2a: ZAKRĘCONE HASŁO immutable content revisions, room pinning.
-- Gameplay project only (glcjetxskjnlbeegirln). No client edits or public RPC for content.
-- The migration is one atomic SQL transaction when applied by the migration runner.
-- Legacy global zh_puzzles remains untouched as archival baseline. The active revision
-- is copied from it once; existing room keys are pinned to this exact baseline.

create table app_private.zh_content_versions (
  version_id bigint generated by default as identity primary key,
  schema_version integer not null default 1 check (schema_version=1),
  source_label text not null check (length(source_label) between 1 and 120),
  created_at timestamptz not null default now()
);

create table app_private.zh_content_puzzles (
  version_id bigint not null references app_private.zh_content_versions(version_id),
  puzzle_key text not null,
  category text not null check (length(trim(category)) between 1 and 100),
  phrase text not null check (length(trim(phrase)) between 1 and 160),
  difficulty integer not null check (difficulty between 1 and 3),
  primary key (version_id,puzzle_key)
);

create table app_private.zh_content_active (
  singleton boolean primary key default true check (singleton),
  version_id bigint not null references app_private.zh_content_versions(version_id)
);

alter table app_private.zh_content_versions enable row level security;
alter table app_private.zh_content_puzzles enable row level security;
alter table app_private.zh_content_active enable row level security;
revoke all on app_private.zh_content_versions, app_private.zh_content_puzzles,
  app_private.zh_content_active from public,anon,authenticated;
revoke all on sequence app_private.zh_content_versions_version_id_seq from public,anon,authenticated;

-- A version and its puzzle rows are append-only. Never edit/replace past values.
create function app_private.zh_reject_revision_mutation()
returns trigger language plpgsql set search_path = ''
as $function$
begin
  raise exception 'Zakręcone Hasło content revision is immutable' using errcode='55000';
end;
$function$;
create trigger zh_versions_immutable before update or delete on app_private.zh_content_versions
for each row execute function app_private.zh_reject_revision_mutation();
create trigger zh_puzzles_immutable before update or delete on app_private.zh_content_puzzles
for each row execute function app_private.zh_reject_revision_mutation();
create trigger zh_versions_no_truncate before truncate on app_private.zh_content_versions
for each statement execute function app_private.zh_reject_revision_mutation();
create trigger zh_puzzles_no_truncate before truncate on app_private.zh_content_puzzles
for each statement execute function app_private.zh_reject_revision_mutation();

-- Guard publication of a later version: 2 distinct categories for each difficulty.
-- Only trusted maintenance SQL can change the active pointer, never client roles.
create function app_private.zh_validate_active_content()
returns trigger language plpgsql set search_path = ''
as $function$
begin
  if exists (
    select 1 from (values (1),(2),(3)) d(difficulty)
    where (select count(distinct p.category) from app_private.zh_content_puzzles p
      where p.version_id=new.version_id and p.difficulty=d.difficulty) < 2
  ) then
    raise exception 'ZH_CONTENT_INCOMPLETE' using errcode='22023';
  end if;
  return new;
end;
$function$;
create trigger zh_validate_active_content before insert or update on app_private.zh_content_active
for each row execute function app_private.zh_validate_active_content();

insert into app_private.zh_content_versions(version_id,source_label)
values(1,'Initial immutable copy of production zh_puzzles');
-- Explicit identity seed must advance the sequence before later versions use DEFAULT.
select setval('app_private.zh_content_versions_version_id_seq',1,true);

insert into app_private.zh_content_puzzles(version_id,puzzle_key,category,phrase,difficulty)
select 1,puzzle_key,category,phrase,difficulty from app_private.zh_puzzles;

-- Explicitly abort instead of silently creating an incomplete version/room binding.
do $check$
begin
 if (select count(*) from app_private.zh_content_puzzles where version_id=1)
     is distinct from (select count(*) from app_private.zh_puzzles)
    or (select count(*) from app_private.zh_content_puzzles where version_id=1) < 6
 then raise exception 'ZH_BASELINE_COPY_INCOMPLETE' using errcode='22023'; end if;
 if exists (
   select 1 from app_private.zh_game_state s
   cross join lateral unnest(s.puzzle_keys) k(puzzle_key)
   where not exists (select 1 from app_private.zh_content_puzzles p
     where p.version_id=1 and p.puzzle_key=k.puzzle_key)
 ) then raise exception 'ZH_LEGACY_ROOM_PUZZLE_MISSING' using errcode='22023'; end if;
end;
$check$;
insert into app_private.zh_content_active(singleton,version_id) values(true,1);

alter table app_private.zh_game_state
  add column content_version_id bigint references app_private.zh_content_versions(version_id);
update app_private.zh_game_state set content_version_id=1;
alter table app_private.zh_game_state alter column content_version_id set not null;

-- Bind game state to exactly one immutable version and valid puzzle keys.
create function app_private.zh_guard_room_content()
returns trigger language plpgsql set search_path = ''
as $function$
begin
  if tg_op='UPDATE' and old.content_version_id is distinct from new.content_version_id then
    raise exception 'ZH_ROOM_CONTENT_VERSION_LOCKED' using errcode='55000';
  end if;
  if cardinality(new.puzzle_keys) < 6
    or new.puzzle_index < 0
    or new.puzzle_index >= cardinality(new.puzzle_keys)
    or (select count(*) from unnest(new.puzzle_keys) k(puzzle_key)
        join app_private.zh_content_puzzles p on p.version_id=new.content_version_id
          and p.puzzle_key=k.puzzle_key) <> cardinality(new.puzzle_keys)
    or (select count(distinct puzzle_key) from unnest(new.puzzle_keys) k(puzzle_key))
          <> cardinality(new.puzzle_keys)
  then
    raise exception 'ZH_ROOM_PUZZLES_INVALID' using errcode='22023';
  end if;
  return new;
end;
$function$;
create trigger zh_room_content_guard before insert or update of
  content_version_id,puzzle_keys,puzzle_index on app_private.zh_game_state
for each row execute function app_private.zh_guard_room_content();

-- Existing engine function, only pinned-bank lookup or initialization changed.
CREATE OR REPLACE FUNCTION app_private.initialize_zh_game_internal(p_room_id uuid)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'app_private', 'pg_temp'
AS $function$
declare
  target_room app_private.platform_rooms%rowtype;
  first_player uuid;
  chosen_keys text[];
  chosen_version bigint;
begin
  select * into target_room
  from app_private.platform_rooms
  where id=p_room_id and game_slug='zakrecone-haslo'
  limit 1;

  if target_room.id is null then
    return false;
  end if;

  select id into first_player
  from app_private.room_players
  where room_id=p_room_id
  order by random()
  limit 1;

  if first_player is null then
    return false;
  end if;

  select version_id into chosen_version
  from app_private.zh_content_active where singleton=true for share;
  if chosen_version is null then raise exception 'ZH_ACTIVE_VERSION_MISSING' using errcode='22023'; end if;

  with candidates as (
    select
      puzzle_key,
      difficulty,
      category,
      row_number() over (
        partition by difficulty, category
        order by random()
      ) as category_pick
    from app_private.zh_content_puzzles
    where version_id=chosen_version
  ),
  picked as (
    (select puzzle_key,difficulty,random() as rnd
     from candidates
     where difficulty=1 and category_pick=1
     order by random()
     limit 2)
    union all
    (select puzzle_key,difficulty,random() as rnd
     from candidates
     where difficulty=2 and category_pick=1
     order by random()
     limit 2)
    union all
    (select puzzle_key,difficulty,random() as rnd
     from candidates
     where difficulty=3 and category_pick=1
     order by random()
     limit 2)
  )
  select array_agg(puzzle_key order by difficulty,rnd)
  into chosen_keys
  from picked;

  if coalesce(cardinality(chosen_keys),0) < 6 then
    raise exception 'Not enough Zakrecone Haslo puzzles';
  end if;

  delete from app_private.zh_game_state where room_id=p_room_id;
  delete from app_private.zh_scores where room_id=p_room_id;

  insert into app_private.zh_scores(room_id,player_id)
  select p_room_id,id
  from app_private.room_players
  where room_id=p_room_id;

  insert into app_private.zh_game_state(
    room_id,puzzle_keys,puzzle_index,active_player_id,round_start_player_id,
    mode,used_letters,last_event,content_version_id
  )
  values(
    p_room_id,chosen_keys,0,first_player,first_player,
    'await_spin','{}'::text[],
    jsonb_build_object('type','round_start','round',1,'at',clock_timestamp()),
    chosen_version
  );

  return true;
end;
$function$
;

-- Existing engine function, only pinned-bank lookup or initialization changed.
CREATE OR REPLACE FUNCTION app_private.get_zh_state_internal(p_code text)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'app_private', 'pg_temp'
AS $function$
declare
  target_room app_private.platform_rooms%rowtype;
  s app_private.zh_game_state%rowtype;
  q app_private.zh_content_puzzles%rowtype;
  reveal_all boolean;
  players_json jsonb;
begin
  select * into target_room
  from app_private.platform_rooms
  where code = upper(trim(p_code))
    and game_slug = 'zakrecone-haslo'
    and expires_at > now()
  limit 1;

  if target_room.id is null then
    return null;
  end if;

  select * into s
  from app_private.zh_game_state
  where room_id = target_room.id;

  if s.room_id is null then
    return null;
  end if;

  select * into q
  from app_private.zh_content_puzzles
  where version_id = s.content_version_id
    and puzzle_key = s.puzzle_keys[s.puzzle_index + 1];
  if q.puzzle_key is null then raise exception 'ZH_PINNED_PUZZLE_MISSING' using errcode='22023'; end if;

  reveal_all := s.mode in ('round_over','game_over');

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'id', p.id,
        'displayName', p.display_name,
        'avatar', p.avatar,
        'totalScore', z.total_score,
        'roundScore', z.round_score,
        'displayScore', z.total_score + z.round_score
      )
      order by p.joined_at, p.id
    ),
    '[]'::jsonb
  )
  into players_json
  from app_private.room_players p
  join app_private.zh_scores z
    on z.room_id = target_room.id and z.player_id = p.id
  where p.room_id = target_room.id;

  return jsonb_build_object(
    'puzzleIndex', s.puzzle_index,
    'puzzleCount', cardinality(s.puzzle_keys),
    'roundNumber', s.puzzle_index + 1,
    'difficulty', q.difficulty,
    'category', q.category,
    'phrase', app_private.zh_mask_phrase(q.phrase, s.used_letters, reveal_all),
    'usedLetters', to_jsonb(s.used_letters),
    'mode', s.mode,
    'activePlayerId', s.active_player_id,
    'roundWinnerId', s.round_winner_id,
    'wheel',
      case
        when s.spin_label is null then null
        else jsonb_build_object(
          'label', s.spin_label,
          'value', s.spin_value,
          'segmentIndex', s.spin_segment
        )
      end,
    'lastEvent', s.last_event,
    'players', players_json
  );
end;
$function$
;

-- Existing engine function, only pinned-bank lookup or initialization changed.
CREATE OR REPLACE FUNCTION app_private.submit_zh_letter_internal(p_code text, p_player_token uuid, p_letter text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'app_private', 'pg_temp'
AS $function$
declare
  target_room app_private.platform_rooms%rowtype;
  player app_private.room_players%rowtype;
  s app_private.zh_game_state%rowtype;
  q app_private.zh_content_puzzles%rowtype;
  letter text := upper(trim(coalesce(p_letter,'')));
  hits integer;
  gained integer;
  next_player uuid;
  event jsonb;
begin
  select * into target_room
  from app_private.platform_rooms
  where code = upper(trim(p_code))
    and game_slug = 'zakrecone-haslo'
    and status = 'active'
    and expires_at > now()
  limit 1;

  if target_room.id is null then
    raise exception 'Game not active';
  end if;

  select * into player
  from app_private.room_players
  where room_id = target_room.id and player_token = p_player_token
  limit 1;

  if player.id is null then
    raise exception 'Player not found';
  end if;

  select * into s
  from app_private.zh_game_state
  where room_id = target_room.id
  for update;

  if s.mode <> 'choose_letter' or s.active_player_id <> player.id or s.spin_value is null then
    raise exception 'Letter cannot be selected now';
  end if;

  if char_length(letter) <> 1
     or letter !~ '^[A-ZĄĆĘŁŃÓŚŹŻ]$'
     or app_private.zh_is_vowel(letter) then
    raise exception 'Choose a consonant';
  end if;

  if letter = any(coalesce(s.used_letters, '{}'::text[])) then
    raise exception 'Letter already used';
  end if;

  select * into q
  from app_private.zh_content_puzzles
  where version_id = s.content_version_id
    and puzzle_key = s.puzzle_keys[s.puzzle_index + 1];
  if q.puzzle_key is null then raise exception 'ZH_PINNED_PUZZLE_MISSING' using errcode='22023'; end if;

  hits := app_private.zh_count_letter(q.phrase, letter);
  gained := hits * s.spin_value;

  if hits > 0 then
    update app_private.zh_scores
    set round_score = round_score + gained
    where room_id = target_room.id and player_id = player.id;

    event := jsonb_build_object(
      'type','letter','playerId',player.id,'playerName',player.display_name,
      'letter',letter,'count',hits,'points',gained,'correct',true,'at',clock_timestamp()
    );

    update app_private.zh_game_state
    set used_letters = array_append(s.used_letters, letter),
        mode = 'await_spin',
        spin_label = null,
        spin_value = null,
        spin_segment = null,
        last_event = event,
        updated_at = now()
    where room_id = target_room.id;
  else
    next_player := app_private.zh_next_player(target_room.id, player.id);

    event := jsonb_build_object(
      'type','letter','playerId',player.id,'playerName',player.display_name,
      'letter',letter,'count',0,'points',0,'correct',false,'at',clock_timestamp()
    );

    update app_private.zh_game_state
    set used_letters = array_append(s.used_letters, letter),
        active_player_id = next_player,
        mode = 'await_spin',
        spin_label = null,
        spin_value = null,
        spin_segment = null,
        last_event = event,
        updated_at = now()
    where room_id = target_room.id;
  end if;

  return event;
end;
$function$
;

-- Existing engine function, only pinned-bank lookup or initialization changed.
CREATE OR REPLACE FUNCTION app_private.submit_zh_vowel_internal(p_code text, p_player_token uuid, p_letter text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'app_private', 'pg_temp'
AS $function$
declare
  target_room app_private.platform_rooms%rowtype;
  player app_private.room_players%rowtype;
  s app_private.zh_game_state%rowtype;
  q app_private.zh_content_puzzles%rowtype;
  letter text := upper(trim(coalesce(p_letter,'')));
  hits integer;
  current_round_score integer;
  next_player uuid;
  event jsonb;
begin
  select * into target_room
  from app_private.platform_rooms
  where code = upper(trim(p_code))
    and game_slug = 'zakrecone-haslo'
    and status = 'active'
    and expires_at > now()
  limit 1;

  if target_room.id is null then
    raise exception 'Game not active';
  end if;

  select * into player
  from app_private.room_players
  where room_id = target_room.id and player_token = p_player_token
  limit 1;

  if player.id is null then
    raise exception 'Player not found';
  end if;

  select * into s
  from app_private.zh_game_state
  where room_id = target_room.id
  for update;

  if s.mode <> 'await_spin' or s.active_player_id <> player.id then
    raise exception 'Vowel cannot be bought now';
  end if;

  if char_length(letter) <> 1 or not app_private.zh_is_vowel(letter) then
    raise exception 'Choose a vowel';
  end if;

  if letter = any(coalesce(s.used_letters, '{}'::text[])) then
    raise exception 'Letter already used';
  end if;

  select round_score into current_round_score
  from app_private.zh_scores
  where room_id = target_room.id and player_id = player.id
  for update;

  if coalesce(current_round_score,0) < 200 then
    raise exception 'Not enough points';
  end if;

  update app_private.zh_scores
  set round_score = round_score - 200
  where room_id = target_room.id and player_id = player.id;

  select * into q
  from app_private.zh_content_puzzles
  where version_id = s.content_version_id
    and puzzle_key = s.puzzle_keys[s.puzzle_index + 1];
  if q.puzzle_key is null then raise exception 'ZH_PINNED_PUZZLE_MISSING' using errcode='22023'; end if;

  hits := app_private.zh_count_letter(q.phrase, letter);

  if hits > 0 then
    event := jsonb_build_object(
      'type','vowel','playerId',player.id,'playerName',player.display_name,
      'letter',letter,'count',hits,'cost',200,'correct',true,'at',clock_timestamp()
    );

    update app_private.zh_game_state
    set used_letters = array_append(s.used_letters, letter),
        last_event = event,
        updated_at = now()
    where room_id = target_room.id;
  else
    next_player := app_private.zh_next_player(target_room.id, player.id);
    event := jsonb_build_object(
      'type','vowel','playerId',player.id,'playerName',player.display_name,
      'letter',letter,'count',0,'cost',200,'correct',false,'at',clock_timestamp()
    );

    update app_private.zh_game_state
    set used_letters = array_append(s.used_letters, letter),
        active_player_id = next_player,
        last_event = event,
        updated_at = now()
    where room_id = target_room.id;
  end if;

  return event;
end;
$function$
;

-- Existing engine function, only pinned-bank lookup or initialization changed.
CREATE OR REPLACE FUNCTION app_private.submit_zh_solve_internal(p_code text, p_player_token uuid, p_guess text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'app_private', 'pg_temp'
AS $function$
declare
  target_room app_private.platform_rooms%rowtype;
  player app_private.room_players%rowtype;
  s app_private.zh_game_state%rowtype;
  q app_private.zh_content_puzzles%rowtype;
  next_player uuid;
  correct boolean;
  event jsonb;
begin
  select * into target_room
  from app_private.platform_rooms
  where code = upper(trim(p_code))
    and game_slug = 'zakrecone-haslo'
    and status = 'active'
    and expires_at > now()
  limit 1;

  if target_room.id is null then
    raise exception 'Game not active';
  end if;

  select * into player
  from app_private.room_players
  where room_id = target_room.id and player_token = p_player_token
  limit 1;

  if player.id is null then
    raise exception 'Player not found';
  end if;

  select * into s
  from app_private.zh_game_state
  where room_id = target_room.id
  for update;

  if s.mode not in ('await_spin','choose_letter') or s.active_player_id <> player.id then
    raise exception 'Cannot solve now';
  end if;

  select * into q
  from app_private.zh_content_puzzles
  where version_id = s.content_version_id
    and puzzle_key = s.puzzle_keys[s.puzzle_index + 1];
  if q.puzzle_key is null then raise exception 'ZH_PINNED_PUZZLE_MISSING' using errcode='22023'; end if;

  correct := app_private.zh_normalize(p_guess) = app_private.zh_normalize(q.phrase);

  if correct then
    update app_private.zh_scores
    set round_score = round_score + 1000
    where room_id = target_room.id and player_id = player.id;

    event := jsonb_build_object(
      'type','solve','playerId',player.id,'playerName',player.display_name,
      'correct',true,'bonus',1000,'at',clock_timestamp()
    );

    update app_private.zh_game_state
    set mode = 'round_over',
        round_winner_id = player.id,
        spin_label = null,
        spin_value = null,
        spin_segment = null,
        last_event = event,
        updated_at = now()
    where room_id = target_room.id;
  else
    next_player := app_private.zh_next_player(target_room.id, player.id);
    event := jsonb_build_object(
      'type','solve','playerId',player.id,'playerName',player.display_name,
      'correct',false,'at',clock_timestamp()
    );

    update app_private.zh_game_state
    set active_player_id = next_player,
        mode = 'await_spin',
        spin_label = null,
        spin_value = null,
        spin_segment = null,
        last_event = event,
        updated_at = now()
    where room_id = target_room.id;
  end if;

  return event;
end;
$function$
;

-- Restrict privileged helpers as well as table access.
revoke all on function app_private.zh_reject_revision_mutation() from public,anon,authenticated;
revoke all on function app_private.zh_validate_active_content() from public,anon,authenticated;
revoke all on function app_private.zh_guard_room_content() from public,anon,authenticated;

-- Postconditions, no update to the historical global bank and no change to scores.
do $post$
begin
 if (select count(*) from app_private.zh_game_state where content_version_id is null)>0
  then raise exception 'ZH_ROOM_VERSION_NOT_PINNED' using errcode='22023'; end if;
 if (select count(*) from app_private.zh_content_puzzles where version_id=1)
   <> (select count(*) from app_private.zh_puzzles)
  then raise exception 'ZH_BASELINE_NOT_IDENTICAL' using errcode='22023'; end if;
end;
$post$;
